### ISSUE TITLE
Playwaze Example Endpoint

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#1]
```
   /getSessions?afterTimestamp=2016-05-16T09:52:18+00:00&afterId=23
   -> { items: [
           {
               state: "updated",
               kind: "session",
               id: "2321",
               modified: "2016-05-16T09:52:18+00:00",
               data: {
                   date: "08/05/2016",
                   starttime: "17:00",
                   endtime: "18:00",
                   Location: "Mens Team Training",
                   Facility: "12",
                   URL: "Brent Mills"
                   groupPlaySession: {
                      name: "Mens Team Training",
                      description: "Two doubles games with members of the team"
                   }
               }
          }
          ]
         next: '/getSessions?afterTimestamp=2016-05-16T09:52:18+00:00&amp;afterId=2321'
   }
```

**Comment by rujenner** [comment]
We're wondering how this data would work with different types of sessions:

1. A course - a sequence of sessions that are treated as a single entity i.e. you sign up to the whole course and are expected to attend every session in that sequence. I'm assuming this would be one record with a start date, end date, number of sessions, days the sessions are on.
2. A sequence of optional sessions like Sunday bike rides i.e. you sign up to join the group and then (using Playwaze) you receive a notification for each ride and say whether you are riding that session or not. Note that with this model some Playwaze administrators set up session sequences up to a year in advance, so I assume you would not want to include each session. As with (1) this should probably be one record.
3. Ad-hoc optional sessions like a diary of triathlon events or cycle sportives. May be about one every two weeks, on any day, and you may want to sign up to 2 or 3. Assume each one would be it's own record. It's slightly different though as you sign up to a particular session within a random sequence. Our Group Play feature here might be called Surrey Triathlon Events with random Group Play fixtures within. So here, we would probably want the nested structure you have illustrated here.

**Comment by nickevansuk** [comment]
#1. A course
That sounds exactly right. Either providing:
- An array of occurrences within the session record (if they are stored on your side individually)
- RRule (iCal) for each course (if they are stored as a recurrence rule on your side):
```
 schedule: [ /* array of recurrence rules */
  {
    dtstart: "2016-06-07T10:00:00",
    dtend: "2016-06-07T13:00:00",
    rrule: { /* https://github.com/coolaj86/rrecurjs */
      "freq": "daily",
      "until": "2016-08-07T10:00:00",
      "byday": ["tu", "th"],
      "byhour": [4],
      "byminute": [30]
    },
    exrule: [ /* exceptions to the recurrence rule */
      "2016-05-07T10:00:00"
    ]
  },
  { /* this session may have originally been part of the rule above, but was rescheduled */
    dtstart: "2016-07-07T10:00:00",
    dtend: "2016-07-07T10:00:00"
  }
]
```

#2. A sequence
As with 1, if they are stored in Playwaze as a recurrence rule better to transmit in the same form, if they are stored as occurrences, then better to provide an array of occurrences. If the metadata is the same for each, then they should be one session with occurrences.

The idea here is to match the internal representation as closely as possible, so we're not generating data from recurrence rules or duplicating meta data for the sake of transmitting it (with the exception of nesting metadata for denormalised storage of parent objects).

#3. Ad-hoc optional sessions
Agree, sounds like the best plan

**Comment by rujenner** [comment]
/getSessions?afterTimestamp=2016-05-16T09:52:18+00:00&afterId=23
-> { items: [
     {
	"id":"pv5rmk1f9t9o",
	"kind":"session",
	"modified":1467809250,
	"state":"updated"
	"data":
	{
		"Date":"31\/07\/2016",
		"StartTime":"15:00",
		"EndTime":"17:00",
		"Facility":"Courts 3 - 4",
		"Location":"Pine Road, Woking”, 
		"lat":12345,
		"lng":77665,
		"URL":"http:\/\/bridtownsquashsessions.com",
		"description":"2 hours of big cardio with Jason Brown",
		"GroupPlaySession":
		{
			“community_id”: "8djada99aa",
			"community":"Bridtown Squash Club",
			"name":"Cardio Training",
			"sport":"Squash"
		}
	}
}  
]
next: '/getSessions?afterTimestamp=2016-05-16T09:52:18+00:00&amp;afterId=2321'
}

**Comment by nickevansuk** [comment]
I notice the new endpoint provided (copied below) does not match the schema. Please ensure that the items in the schema match:
https://www.openactive.io/realtime-paged-data-exchange/#example

Given that courses and sessions are paging through two different tables in the database, perhaps two endpoints would be more appropriate? One for courses, and one for sessions?

```
{
  "Result": {
    "Courseitems": [
      {
        "data": {},
        "id": "936ou6r9im1",
        "kind": "course",
        "modified": 1490104361,
        "state": "updated"
      }
    ],
    "Sessionitems": [
      {
        "data": {},
        "id": "d5bnntvhkdfe",
        "kind": "session",
        "modified": 1488952442,
        "state": "updated"
      },
      {
        "data": {},
        "id": "4kc1eao8dhb6f8",
        "kind": "session",
        "modified": 1490104253,
        "state": "updated"
      }
    ]
  }
}
```
