### ISSUE TITLE
Paging issue with last page

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#102]
http://8dcdb132.ngrok.io/api/openactive/event_types?afterId=z25wazieak1h&afterTimestamp=1497597551 returns only one item, and the same next URL.

This is likely because the query being used for paging isn't quite right: it should be `WHERE (MODIFIEDDATE = @afterTimestamp AND ID > @afterId) OR (MODIFIEDDATE > @afterTimestamp)` note the `>` and not `>=`

**Comment by jopotts** [comment]
Paging should now be working as expected.
