### ISSUE TITLE
BookingBug

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#108]
We've turned on OpenActive for Central Health Physiotherapy and it'd be great to get some feedback on the API. The endpoint is now accessible at:

https://uk.bookingbug.com/api/v1/openactive/37701/sessions

Something that is immediately apparent is that we are marking historical events as deleted. Should we just avoid returning them? The third page has some bookable events on it.

https://uk.bookingbug.com/api/v1/openactive/37701/sessions?afterTimestamp=2016-04-13T16%3A32%3A04Z&afterId=12952719&limit=500

**Comment by philjackson** [comment]
There were some tiny tweaks I've made to the output of the event feed. I'll put it here and update it if I've missed anything:

    {
      "@context": [
        "https://www.openactive.io/ns/oa.jsonld",
        "https://www.openactive.io/ns-beta/oa.jsonld"
      ],
      "data": [
        {
          "type": "Event",
          "identifier": 19435320,
          "id": "https://uk.bookingbug.com/api/v1/openactive/37701/sessions/19435320",

          "state": "Updated",
          "kind": "Session",
          "modified": "2017-08-16T23:21:13Z",

          "name": "Monday Antenatal Pilates 12pm",
          "description": "Monday Antenatal Pilates 12pm",
          "duration": "PT1H",
          "maximumAttendeeCapacity": 6,
          "remainingAttendeeCapacity": 6,
          "startDate": "2018-03-05T12:00:00+00:00",
          "url": "https://uk.bookingbug.com/home/37701-Central-Health-Physiotherapy",
          "organizer": {
            "name": "Central Health Physiotherapy",
            "type": "Organization",
            "url": "www.central-health.com"
          },
          "location": {
            "address": {
              "addressLocality": "",
              "addressRegion": "London",
              "postalCode": "WC2A 1QS",
              "streetAddress": "Chancery House, 53-64 Chancery Lane",
              "type": "Address"
            },
            "openingHoursSpecification": [],
            "type": "Place"
          }
        }
      ]
    }

**Comment by philjackson** [comment]
Looking great, I've inlined some comments below:

* There are no images which we would recommend providing, this will enrich the booking experience via the brokers by a large margin.
* If you have geo data we'd highly encourage its inclusion in the location. This makes the events far more likely to be included on broker maps as a pin.

```json
{
  "state": "updated",
  "kind": "session",
  "id": 19746963,
  "modified": "2017-09-15T23:14:26Z",
  "data": {
    "type": "Event",
    "name": "Wednesday Improvers Pilates - 12pm",
    "description": "Wednesday Improvers Pilates - 12pm",
    "startDate": "2018-04-04T12:00:00+01:00",
    "duration": "PT1H",
```

* It's good to include an endDate here too. 
* We'd recommend using GMT dates, allowing implementers of the data to apply localisation. 

```json
    "url": "https://uk.bookingbug.com/home/37701-Central-Health-Physiotherapy",
    "maximumAttendeeCapacity": 6,
    "remainingAttendeeCapacity": 6,
    "location": {
      "type": "Place",
      "address": {
        "type": "Address",
        "streetAddress": "Chancery House, 53-64 Chancery Lane",
        "addressLocality": "",
        "addressRegion": "London",
        "postalCode": "WC2A 1QS"
      },
      "openingHoursSpecification": []
    },
    "organizer": {
      "type": "Organization",
      "url": "www.central-health.com",
```

* All URLs should be absolute (including the protocol).

```json
      "name": "Central Health Physiotherapy"
    }
  }
}
```

**Comment by edclements** [comment]
Thanks for the feedback.
