### ISSUE TITLE
England Netball

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#109]
See here: http://data.englandnetball.co.uk/

**Comment by philjackson** [comment]
Please see sample of feed below. I'm not sure what the following fields would represent:

* `"num_of_days": null`
* `"day_duration": null`

    {
      "license": "https://creativecommons.org/licenses/by/4.0/",
      "next": "http://api.letsride.co.uk/public/v1/rides?afterTimestamp=1970-01-01+01%3A02%3A09&afterId=1234",
      "items": {
        "state": "updated",
        "kind": "session",
        "id": 2,
        "modified": "2014-04-29T12:14:35",
        "data": {
          "@context": [
            "https://www.openactive.io/ns/oa.jsonld",
            "https://www.openactive.io/ns-beta/oa.jsonld"
          ],
          "type": "Event",
          "identifier": 2,
          "id": "/api/openactive/sessions/2",
          "description": "Event specific description (as opposed to the brand/programme)",
          "programme": {
            "type": "Brand",
            "identifier": "B2N000002",
            "name": "Back to Netball",
            "url": "https://www.englandnetball.co.uk/backtonetball/",
            "description": "Running across England since 2010, over 60,000 women have taken part in Back to Netball and realised the benefits of getting involved."
          },
          "startDate": "2015-09-04T20:30:00Z",
          "endDate": "2015-09-04T21:30:00Z",
          "ageRange": "16-55",
          "leader": {
            "type": "Person",
            "givenName": "Joe",
            "familyName": "Bloggs",
            "email": "joe@example.com",
            "telephone": "01234 728381"
          },
          "sameAs": [
            "https://twitter.com/netball",
            "https://facebook.com/netball"
          ],
          "location": {
            "type": "Location",
            "address": {
              "type": "PostalAddress",
              "streetAddress": "Raynes Park High School, 46A West Barnes Lane",
              "addressLocality": "New Malden",
              "addressRegion": "London",
              "postalCode": "NW5 3DU",
              "geo": {
                "latitude": 51.403443,
                "longitude": -0.2369089
              }
            }
          },
          "offer": {
            "type": "Offer",
            "price": 3.70,
            "priceCurrency": "GBP"
          }
        }
      }
    }
