### ISSUE TITLE
Athliit Example Endpoint

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#11]
Please provide example JSON response here

**Comment by TheLegendOfProgramming** [comment]
{
nextUrl: "http://athliit.app/api/openactive/events/1435259096",
items: [
{
state: "updated",
id: 1,
kind: "event",
modified: 1466465581,
data: {
id: 1,
name: "Amir Gislason",
slug: "amir-gislason",
description: "Molestiae nulla reiciendis libero ut. Esse nulla quae molestiae repellendus velit. Quo architecto voluptates excepturi qui vero numquam magni. Odit ducimus sed quo.",
url: "http://athliit.app/mikenta/event/amir-gislason",
show_participants: true,
start: {
date: "2016-06-07 12:13:44.000000",
timezone_type: 3,
timezone: "Europe/Copenhagen"
},
end: {
date: "2016-03-14 19:58:43.000000",
timezone_type: 3,
timezone: "Europe/Copenhagen"
},
last_ticket_day: {
date: "2016-06-20 03:20:49.000000",
timezone_type: 3,
timezone: "Europe/Copenhagen"
},
page: {
id: 1,
name: "Mikenta",
slug: "mikenta",
url: "http://athliit.app/mikenta",
type: "club"
}
}
}
]
}

**Comment by nickevansuk** [comment]
This looks great! Note that Markdown is supported in these comments, so you can use *\`\`\`* to keep code formatting.

Some thoughts:

- I notice you've opted for just modified timestamp in the event, have you checked out the options in [4.3](https://www.openactive.io/realtime-paged-data-exchange/#example-implementations). Either the modified timestamp must be unique, or you also include a modified ID.
- Is there any more description data available from the page? Or image urls?
- Is there any more data available for the event (e.g. price? images urls?)
- Better include as much data as you have available if possible, to match what's available on the public page and public event.

**Comment by TheLegendOfProgramming** [comment]
I’ll remember that tip with the ````. The timestamp is unique, and returns all events updated after or at the timestamp. We opted for timestamp because you can get all the data until beggining of time, and then it sends only the new updates. If you also specify the ID, it returns all the id’s after that one, given that the objects in the response are orderedBy(‘id’,’asc’). The data that we send is handled by Mattias, and I talked with him, so if we have anything to add there it will be added. I hope I got it right, but if there’s something wrong with the way i did the nextUrl it please let me know and ill redo, I’m still quite new at this 🙂.

Thanks,

Mircea

----
Mircea Vlad Burac
Backend Developer - Athliit
+45 52 70 87 77 | mircea@athliit.com | Athliit.com <http://athliit.com/>

**Comment by TheLegendOfProgramming** [comment]
Update to First Example, with more data:
"
{

    "nextUrl": "http://athliit.app/api/openactive/events/1435259097",
    "items": [
        {
            "state": "updated",
            "id": 1,
            "kind": "event",
            "modified": 1467030449,
            "data": {
                "id": 1,
                "name": "Magdalena Gulgowski",
                "slug": "magdalena-gulgowski",
                "description": "Placeat voluptas nobis et laboriosam vel quibusdam ut. Sed amet nobis reprehenderit. Magnam nihil impedit voluptas officia iste molestiae aliquid. Consectetur et sed non quia.",
                "url": "http://athliit.app/mikenta/event/magdalena-gulgowski",
                "show_participants": true,
                "start": {
                    "date": "2015-12-01 22:26:30.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Copenhagen"
                },
                "end": {
                    "date": "2016-02-16 00:40:57.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Copenhagen"
                },
                "last_ticket_day": {
                    "date": "2016-06-26 20:09:55.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Copenhagen"
                },
                "location": {
                    "id": 286,
                    "name": "",
                    "description": "",
                    "lat": -14.146419,
                    "lng": 172.948758,
                    "city": "East Robinmouth",
                    "country": "Canada",
                    "street": "Prairie",
                    "type": "",
                    "place_id": "",
                    "nice_name": "East Robinmouth, Canada"
                },
                "image": "http://athliit.app/images/events/51309457ba2b8688e7bccd5878dd7e28.jpg",
                "page": {
                    "id": 1,
                    "name": "Mikenta",
                    "slug": "mikenta",
                    "url": "http://athliit.app/mikenta",
                    "type": "club",
                    "avatar": "http://athliit.app/images/pages/ebf5bd88e4037a4c42c1f59df520ea7b.jpg",
                    "cover": "http://athliit.app/images/pages/b6bc84ec6aa413334a725d4732d6d303.jpg",
                    "images": [
                        {
                            "filename": "ebf5bd88e4037a4c42c1f59df520ea7b.jpg",
                            "type": "avatar",
                            "url": "http://athliit.app/images/pages/ebf5bd88e4037a4c42c1f59df520ea7b.jpg"
                        },
                        {
                            "filename": "b6bc84ec6aa413334a725d4732d6d303.jpg",
                            "type": "cover",
                            "url": "http://athliit.app/images/pages/b6bc84ec6aa413334a725d4732d6d303.jpg"
                        }
                    ]
                }
            }
        },
"

**Comment by nickevansuk** [comment]
How are you getting on with this?

We're about to draft a new version of the standard, so to keep this in line with that (so that you're ahead of this), please also add a `license` to each page as follows:
```
{
  "next": "/prod/getSessions?afterTimestamp=2016-05-23T15:42:05.568Z&afterID=2055",
  "items": [
    {
      ...
    }
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
```

See the issue in the main spec for more info: https://github.com/openactive/realtime-paged-data-exchange/issues/34

**Comment by TheLegendOfProgramming** [comment]
Latest Json Example:
"
{

    "nextUrl": "http://athliit.app/api/openactive/events/2016-06-29%2015:32:45",
    "items": [
        {
            "state": "updated",
            "id": 6,
            "kind": "session",
            "modified": {
                "date": "2016-06-29 15:32:44.000000",
                "timezone_type": 3,
                "timezone": "Europe/Copenhagen"
            },
            "data": {
                "id": 6,
                "name": "Wendell Stanton",
                "slug": "wendell-stanton",
                "description": "In itaque voluptatibus tenetur sit velit. Quis maiores consectetur quae quibusdam enim alias. Ut quasi ipsam enim qui tenetur.",
                "url": "http://athliit.app/boyle-crooks/event/wendell-stanton",
                "show_participants": true,
                "start": {
                    "date": "2016-01-23 07:35:48.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Copenhagen"
                },
                "end": {
                    "date": "2016-04-11 14:00:57.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Copenhagen"
                },
                "last_ticket_day": {
                    "date": "2016-06-28 19:23:51.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Copenhagen"
                },
                "location": {
                    "id": 63,
                    "name": "",
                    "description": "",
                    "lat": 8.156278,
                    "lng": 145.768781,
                    "city": "Jacobsmouth",
                    "country": "Spain",
                    "street": "Mountains",
                    "type": "",
                    "place_id": "",
                    "nice_name": "Jacobsmouth, Spain"
                },
                "image": "http://athliit.app/images/events/fc404aa0687246ee287d5d5a98f8548f.jpg",
                "page": {
                    "id": 3,
                    "name": "Boyle-Crooks",
                    "slug": "boyle-crooks",
                    "url": "http://athliit.app/boyle-crooks",
                    "type": "instructor",
                    "avatar": "http://athliit.app/images/placeholder.jpg",
                    "cover": "http://athliit.app/images/placeholder.jpg",
                    "images": [ ]
                }
            }
        }
    ],
    "license": "https://creativecommons.org/licenses/by/4.0/"

}
"
Note:
-afterDate changed from Unix Timestamp to DateTime
-when faced with a page with no items, nextUrl will be the afterDate until new update
-items showed when using a url with afterDate will be the ones with modified >= afterDate, and it will be the same for afterID; it can be changed to only > if desired

**Comment by nickevansuk** [comment]
We had the same conversation with GoodGym yesterday (https://github.com/openactive/activation/issues/15).

As we said then, crucially the sessions returned in a page should be _after_ the URL specifies. **>** instead of **>=**.

Hence the last page should not contain any items, but should contain a next URL.

The pseudo code for the query is below:

- query = Session.query().filter((**Session.modified == queryParams.afterTimestamp** && **Session.id > queryParams.afterId**) || (**Session.modified > queryParams.afterTimestamp**));

I've made a note to make this explicit in the standard (https://github.com/openactive/realtime-paged-data-exchange/issues/35)

**Comment by nickevansuk** [comment]
Do you have an endpoint URL we can look at to test?

**Comment by TheLegendOfProgramming** [comment]
Not yet, it has to get pushed to production. Right now my code is only in my test environment. Is tomorrow okay? The url should be http://athliit.com/api/openactive/events/1467198867 when it's done.

**Comment by nickevansuk** [comment]
No problem, look forward to it

**Comment by TheLegendOfProgramming** [comment]
Well, it still hasn't gotten to production, and I don't quite have power over that, but I'll let you know when it's actually working :)

**Comment by TheLegendOfProgramming** [comment]
Finally, it's up and running , you can use this url for testing : https://athliit.com/api/openactive/events/2016-04-27%2020:20:00

**Comment by nickevansuk** [comment]
Now that it's live I've had a chance to run it through the validator (http://validator.openactive.io), and noticed a few issues. I'll raise them under this milestone: https://github.com/openactive/activation/milestone/13 so you we can keep a track of them between us.
