### ISSUE TITLE
Ensure that deleted items are included in the feed

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#12]
Deleted items must be included in the feed to ensure consistency of data transfer, suggest the use of a "deleted" field in the database.

Raised an issue in the docs here: https://github.com/openactive/realtime-paged-data-exchange/issues/30

**Comment by manzan46** [comment]
This is now good too

**Comment by nickevansuk** [comment]
Great thanks so much, enjoy your holiday!
