### ISSUE TITLE
Use "ageRange" instead of custom "ageGroup" property

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#124]
Applying rules:
- ageRange should contain a QuantifiedValue object (https://github.com/openactive/developer-microsite/issues/18)

Not like this:

```javascript
  "ageGroup": "9-11",
```

Like this:

```javascript
  "ageRange": {
     "type": "QuantitativeValue",
     "minValue": 9,
     "maxValue": 11 
  },
```

**Comment by daniel-intosport** [comment]
I'm not sure we can present this data in this way as it's not defined like this within the Monitoring System.  There are no age ranges/groups on any of the other programmes so this data is not available.

**Comment by nickevansuk** [comment]
This is only for NYC data from what I understand, is it not possible to split your "ageGroup" field which contains e.g. "9-11" by the "-" character to populate this:
```
  "ageRange": {
     "type": "QuantifiedValue",
     "minValue": 9,
     "maxValue": 11 
  }
```

**Comment by nickevansuk** [comment]
Could you point to a page where this exists to help us test this?

**Comment by nickevansuk** [comment]
Great thanks, have been able to QA now.

`minValue` and `maxValue` should be integer, as below. And "type" should be "`QuantitativeValue`" instead of "`QuantifiedValue`". This was a typo on a previous version of the spec.

```
  "ageRange": {
    "type": "QuantitativeValue",
    "minValue": 11,
    "maxValue": 16
  },
```

**Comment by nickevansuk** [comment]
The typo `QuantifiedValue` still needs to be fixed.

**Comment by nickevansuk** [comment]
Great!
