### ISSUE TITLE
Include level wherever possible

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#126]
Applying rules:
- Include level wherever possible (https://github.com/openactive/developer-microsite/issues/20)

Feedback welcome on this proposal:
- https://github.com/openactive/modelling-opportunity-data/issues/82

Assuming all of the content provided by England Netball is beginner friendly, simply include the below (following the [existing specification](https://www.openactive.io/modelling-opportunity-data/#categorising-events) rather than the new proposal above):

```javascript
    "level": [ "beginner" ]
```

**Comment by daniel-intosport** [comment]
This data is not captured within the monitoring system.  We will have to speak to England Netball over whether it is safe to assume that all programmes are beginner friendly.

**Comment by daniel-intosport** [comment]
Unfortunately I have been told by EN that we can't assume that it is all beginner friendly so we will have to omit this information from the api

**Comment by nickevansuk** [comment]
Is it possible to assign "level" by programme? E.g. all "Back to Netball" sessions are beginner? In which case this could be included in the same way as URL and video for the programme.

**Comment by nickevansuk** [comment]
Great, assume that `"isCoached": true` wasn't useful
