### ISSUE TITLE
Include genderRestriction wherever possible

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#127]
Applying rules:
- Include genderRestriction wherever possible (https://github.com/openactive/developer-microsite/issues/21)

Feedback welcome on this proposal:
- https://github.com/openactive/modelling-opportunity-data/issues/69

Assuming all of the content provided by England Netball is female-only, simply include the below (the proposal above has been included in the next release of the spec):

```javascript
    "genderRestriction": "https://www.openactive.io/ns#Female"
```

**Comment by kent-gosweat** [comment]
Is this a binary gender restriction? M/F?

**Comment by nickevansuk** [comment]
@kent-gosweat see proposal https://github.com/openactive/modelling-opportunity-data/issues/69 for more info - it's M, F, or Mixed at present. Comments on proposal very welcome!

**Comment by daniel-intosport** [comment]
There is no gender definition for programmes within the Monitoring System.  We will speak to England Netball if it is safe to assume that the programmes included on the api feed are female only.

**Comment by daniel-somersault** [comment]
@nickevansuk spoke to EN about this and we can't assume that is the case so it will probably have to be omitted from the feed

**Comment by nickevansuk** [comment]
That's a shame, but shouldn't preclude data from being included in e.g. This Girl Can as Netball is fairly obvious in this respect, provided you can include "level" (as per https://github.com/openactive/activation/issues/126).
