### ISSUE TITLE
Include organizer as required field

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#128]
Applying rules:
- Include organizer as required field

Like this:

```javascript
      "organizer": {
        "identifier": 12321, /* Include an organiser ID if you have one, as this is used for organiser-based approval */
        "name": "Toxteth Firefit Hub" /* notice you have an Organiser visible on the website (e.g. https://www.englandnetball.co.uk/?pagename=session&sessionid=[61976&NN005356 ). */ 
      },
```

**Comment by daniel-somersault** [comment]
@nickevansuk Hi Nick - not quite sure what this relates to, this is just the venue name.  The only information passed in the other API for England Netballs website is: contact name, number & email and the venue name and address all of which are included elsewhere.  It's possible they have labelled it differently on the Session Finder but I can't access it at the moment as they seem to be having problems with their website over the last few days.

**Comment by nickevansuk** [comment]
@daniel-somersault from what I recall the venue is labelled as the organiser in the UI.

This might well be accurate, as the venue could be the “organisation ultimately responsible for the event” (the definition of organiser), or otherwise this might be England Netball.

On to check with Chris perhaps?

If the venue is ultimately responsible then the name and identifier should be duplicated into the `organizer` props from the `location` props

If England Netball is ultimately responsible then use the `name` “England Netball” and the `url` of their website inside `organizer`

**Comment by daniel-somersault** [comment]
@nickevansuk will be England Netball as the organizer

**Comment by nickevansuk** [comment]
This is missing the `"type"` property:

```
"organizer": {
  "name": "England Netball",
  "url": "https://www.englandnetball.co.uk"
}
```

should be

```
"organizer": {
  "type": "Organization",
  "name": "England Netball",
  "url": "https://www.englandnetball.co.uk"
}
```

**Comment by nickevansuk** [comment]
Looks good!
