### ISSUE TITLE
For ageRange, at least one of minValue or maxValue must be supplied

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#136]
Applying rules:
- For ageRange, at least one of minValue or maxValue must be supplied ( https://github.com/openactive/developer-microsite/issues/27 ) 

Feedback request:
- Please feel free to feedback on this [ageRange](https://github.com/openactive/modelling-opportunity-data/issues/68) proposal with your thoughts on this approach

Not like this:

```javascript
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "ageRange": {
    "type": "QuantitativeValue"
  }
}
```

Like this:

```javascript
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event"
  /* For ageRange, at least one of minValue or maxValue must be supplied, otherwise the ageRange property should be omitted */
}
```

**Comment by nickevansuk** [comment]
Unable to find test data as RPDE is currently broken

**Comment by nickevansuk** [comment]
Could you please help me find a page which has this data in to QAA?

**Comment by nickevansuk** [comment]
Ok found one in:
http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=52698&afterId=3549

Check out:
https://www.letsride.co.uk/rides/glasgow-special-sky-ride-local-with-free-wheel-north-12-miler

None of the ageRange info is coming through to the feed currently.

I'd recommend for "minValue" just use the minimum of the lowest ages on the list (or 16 if nothing lower is specified), and for "maxValue" using the maximum of the highest ages on the list, and leaving "maxValue" out for where "Adults 16+ only" is included.

### Example 1
`Children aged 8-15*, Children aged 11-15*, Adults 16+ only, Children aged 5-15*`

Would be:
```
  "ageRange": {
    "type": "QuantitativeValue",
    "minValue": 5
  }
```

### Example 2
`Children aged 8-15*, Children aged 11-15*, Children aged 5-15*`

Would be:
```
  "ageRange": {
    "type": "QuantitativeValue",
    "minValue": 5,
    "maxValue":15
  }
```

**Comment by nickevansuk** [comment]
Quick spot check, the following are incorrect....

In this feed:
http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=52698&afterId=3549

https://www.letsride.co.uk/rides/wakefield-tour-de-yorkshire-route-23-miler-2 
- Website: Adults 16+ only
- Feed: "minValue": 11

https://www.letsride.co.uk/rides/glasgow-special-sky-ride-local-with-free-wheel-north-12-miler
- Website: Children aged 8-15*, Children aged 11-15*, Adults 16+ only, Children aged 5-15*
- Feed: "minValue": 8

https://www.letsride.co.uk/rides/heading-out-to-horning
- Website: None (so default 16+)
- Feed: "minValue": 5

**Comment by nickevansuk** [comment]
Also note it should be "QuantitativeValue" instead of "QuantifiedValue":

```
"ageRange": {
    "type": "QuantifiedValue",
    "minValue": 5
  },
```

**Comment by sevenpointsix** [comment]
@nickevansuk Currently our data feed is reporting "AgeRange" as the range of people who attended that ride.

Should it actually report on the suitability of the ride, i.e., the age ranges for whom the ride was meant?

**Comment by nickevansuk** [comment]
Yes that's right, "the age ranges for whom the ride was meant" is exactly it

**Comment by sevenpointsix** [comment]
@nickevansuk The minimum age for an "HSBC Ride Social" ride is defined in our database as five. This isn't displayed on the front-end of the website, but that's an issue for the website team, I think. The API is correctly reporting what I can see in the database, which is that the minimum age for a ride such as "Heading out to Horning" is 5.

**Comment by nickevansuk** [comment]
Just for traceability of decisions here, from Cazz: "Regarding the age range, B has clarified that there are two states – Adult only (over 16) and anyone (no age specified) and Chris will look at how to reflect that in the feed"

So https://www.letsride.co.uk/rides/heading-out-to-horning is indeed suitable for "anyone" including kids, which means that leaving it with 5+ and having it included in Change4Life is desirable.

Hence no change is required.
