### ISSUE TITLE
Empty strings and unknown values should be treated as null properties

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#140]
Applying rules:
- Empty strings and unknown values should be treated as null properties and not included for the items where they are null (https://github.com/openactive/developer-microsite/issues/10) 

Not like this:

```javascript
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "meetingPoint": "",
  "attendeeInstructions": null,
  "britishcycling:gpxFile": "unknown",
  "britishcycling:publicTransport": 0,
  "britishcycling:publicTransportDetails": ""
}
```

Like this:

```javascript
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event"
}
```

**Comment by nickevansuk** [comment]
All data seems to now have:

```
"description": null,
"beta:formattedDescription": null,
```

Perhaps related to this change?

**Comment by nickevansuk** [comment]
Description still seems to be missing on many rides, including on this page: http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1985&afterId=7941

Yet the description is visible on the pages associated with the rides...

**Comment by sevenpointsix** [comment]
Do you have an example of a specific ride here @nickevansuk ?

**Comment by nickevansuk** [comment]
Sure see https://www.letsride.co.uk/rides/brock-deer-spotting-1 in http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1985&afterId=7941, and note that the description "Enjoy a wonderful time cycling through the New Forest National Park on this route of just over 7 miles.  If you're lucky you'll catch a glimpse of deer, ponies and donkeys along your way.  This route is definitely one for the lover of the great outdoors and will leave you wanting more....you'll be back!" is not visible anywhere
