### ISSUE TITLE
GeoCoordinates must be specified as decimal values

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#149]
Applying rules:
- GeoCoordinates must be specified as decimal values (https://github.com/openactive/developer-microsite/issues/30) 

Not like this:

```javascript
"geo": {
  "type": "GeoCoordinates",
  "latitude": "52.60",
  "longitude": "-1.33"
}
```

Like this:

```javascript
"geo": {
  "type": "GeoCoordinates",
  "latitude": 52.60, /* GeoCoordinates must be specified as decimal values */
  "longitude": -1.33 /* GeoCoordinates must be specified as decimal values */
}
```

**Comment by matthew-coffey** [comment]
I'd suggest any references in the modelling data are updated to reflect this requirement as that's what I was copying: https://www.openactive.io/modelling-opportunity-data/#describing-places
