### ISSUE TITLE
Include the next URL on an empty page

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#15]
The next URL on an empty page should match the last available item (as the page shows everything after the item, which is nothing in the case of the last item).

Note: have added this issue the docs https://github.com/openactive/realtime-paged-data-exchange/issues/29

**Comment by manzan46** [comment]
All good too if the if empty the last back come back with  the last modified, example for 2017 date https://www.goodgym.org//getHappenings?afterTimestamp=2016-07-04%2012:48:14%20UTC&afterID=2208

**Comment by nickevansuk** [comment]
Crucially the sessions returned in a page should be _after_ the URL specifies. `>` instead of `>=`.

Hence the last page should not contain any items.

The pseudo code for the query is below:

- query = Session.query().filter((*Session.modified == queryParams.afterTimestamp* && *Session.id > queryParams.afterId*) || (*Session.modified > queryParams.afterTimestamp*));

**Comment by manzan46** [comment]
OK will fix this one.

**Comment by manzan46** [comment]
This should be fix now, https://www.goodgym.org/getHappenings?afterTimestamp=2017-07-04%2012:48:15%20UTC&afterID=2208

**Comment by nickevansuk** [comment]
Perfect
