### ISSUE TITLE
Use activities from the activity list

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#153]
Applying rules:
- Use activities from the activity list ( https://github.com/openactive/developer-microsite/issues/38 )

(Note: also included the name of the componentEvent for data user convenience, see below)

Not like this:

```javascript
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "activity": [
    "Duathlon"
  ]
}
```

Like this:

```javascript
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "activity": [
    {
      "type": "Concept",
      "id": "https://www.openactive.io/activity-list/#7a0d4399-d7a2-43e4-b9dc-5bf88c7a7eea",
      "prefLabel": "Duathlon",
      "inScheme": "https://www.openactive.io/activity-list/"
    }
  ]
}
```

Not like this:

```javascript
"btf:componentEvent": [
  {
    "type": "Event",
    "identifier": "stage-78756",
    "activity": "swim",
    "distance": {
      "value": 160,
      "unitCode": "MTR"
    },
    "btf:swimtype": "Pool",
    "order": 1
  }
]
```

Like this:

```javascript
"btf:componentEvent": [
  {
    "type": "Event",
    "identifier": "stage-78756",
    "name": "Swim", /* Note also included the name of the componentEvent for convenience */
    "activity": {
      "type": "Concept",
      "id": "https://www.openactive.io/activity-list/#2750229d-b725-4171-9276-376be913957c",
      "prefLabel": "Swimming",
      "inScheme": "https://www.openactive.io/activity-list/"
    },
    "distance": {
      "value": 160,
      "unitCode": "MTR"
    },
    "btf:swimtype": "Pool",
    "order": 1
  }
]
```

**Comment by matthew-coffey** [comment]
So this is actually quite hard. I've changed how it works in the componentEvent as that will always only be Swimming, Cycling or Running.

For the overall event activity, I've change the current activity to be "btf:raceType" to distinguish between a Sprint, Super Sprint, Standard or Long Distance Triathlon (for example) as this is still useful information.

However, then try to provide the required "Activity" field, not all our events will fall into one of the three categories of Triathlon, Duathlon or Aquathlon. We have some Aquabike events, open water swimming events, some Swim-Run events and then very occasionally some weird format like a Run-Bike or something. I'm not sure how to deal with these. Even if Aquabike was added to the Activity List, there's always the chance a random configuration of "stages" will be created which won't fit the logic, and I'm not sure how we display that?

**Comment by matthew-coffey** [comment]
What I've done for now is, if the activity doesn't exist at all (eg. some random bike/run) default to triathlon. And then for Aquabike, which is a semi-regular activity, which doesn't exist on the list I'm just showing:
```
{
      "type": "Concept",
      "id": "https://www.openactive.io/activity-list/",
      "prefLabel": "Aquabike",
      "inScheme": "https://www.openactive.io/activity-list/"
}
```

**Comment by nickevansuk** [comment]
Great to see! This is a good example where the best plan is feeding back into the activity list to add activities (which British Triathlon are well placed to do for your specialist area).

As well as Aquabike, would you also recommend that any user activity search would be able to drill down into more granular types of Triathlon, to help end users to find what they're looking for? (e.g. “Super Sprint Triathlon”, “Sprint Distance Triathlon”, “Standard Distance Triathlon”, “Middle Distance Triathlon”, “Relay”)?

**Comment by samhibberd** [comment]
Event name suggestions:
- Super Sprint Triathlon
- Sprint Triathlon
- Standard Triathlon / Olympic Distance Triathlon
- Middle Distance Triathlon / 70.3 / Half Ironman
- Long Distance Triathlon / Ironman

Team / Relay could be a sub category for each of these

**Comment by matthew-coffey** [comment]
I think that would be useful yes - which is why I've added the btf:raceType property for now - I'm not sure if that would be better done in the activity list though.

Looking at the activity list as it is currently doesn't really go into that level of breakdown. You have "Running" and not "Marathon", "Half Marathon", "10K" etc so I'm not sure if it goes against the idea of the activity list but if not.

For info, our race types (which are not necessarily perfect for OpenActive's requirements) are currently:

- Super Sprint Triathlon
- Sprint Distance Triathlon
- Standard Distance Triathlon
- Middle Distance Triathlon
- Long Distance Triathlon
- Duathlon
- Aquathlon
- Cross Triathlon
- Cross Duathlon
- Winter Triathlon
- Childrens Triathlon
- Childrens Duathlon
- Childrens Aquathlon
- Aquabike
- GO TRI
- Swim
- Relay

**Comment by nickevansuk** [comment]
Also @matthew-coffey just noticed GO TRI in the list, which is a programme rather than an activity: see here https://github.com/openactive/activation/issues/155

**Comment by nickevansuk** [comment]
@matthew-coffey also do go ahead and use the following (as `"id": "https://www.openactive.io/activity-list/"` is an invalid id for Aquabike as it stands):

- https://github.com/openactive/activity-list/issues/14

**Comment by matthew-coffey** [comment]
Yes I think it would be better if you use ageRange, though currently we can't show that, there are certainly problems caused with the way we do it currently (how do you distinguish between a GO TRI triathlon and a GO TRI duathlon?) so not recommending OpenActive adopts the same.

From my perspective, people could have a go at working out the type of race (sprint/standard/middle) using the distance field, but I would assume might be more handy if there was a fixed record? I believe that within those categories there is scope for changes.

For example, a standard distance triathlon is normally 1500m swim, 40km bike, 10km run but organisers could create one with a 1600m swim, 42km bike and 9.5km run and that would be okay as long as it was advertised as a standard distance.

Therefore any consumers of the API wouldn't necessarily be able to work out what it should be if we don't categorise it from our side.

**Comment by nickevansuk** [comment]
Fantastic comments! Have added to https://github.com/openactive/activity-list/issues/15 to flag as something to sort out under the new activity list governance (currently being conceived).

Will close this issue as the immediate requirement has been fulfilled

**Comment by nickevansuk** [comment]
Reopening this as just seen:

```
"activity": [
          {
            "type": "Concept",
            "id": "https://www.openactive.io/activity-list/",
            "prefLabel": "Run/Bike",
            "inScheme": "https://www.openactive.io/activity-list/"
          }
        ],
```

As discussed please do add a new issue here for this: https://github.com/openactive/activity-list/issues
