### ISSUE TITLE
Include the URL of the session page in the data block

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#16]
It's important to include a URL for the related session page within the data block.

There's an open issue for this already on the docs: https://github.com/openactive/realtime-paged-data-exchange/issues/20

**Comment by manzan46** [comment]
All fix, check it out here https://www.goodgym.org//getHappenings?afterTimestamp=2016-05-24%2012:48:14%20UTC&afterID=2208

**Comment by nickevansuk** [comment]
Fantastic! Looks good!
