### ISSUE TITLE
Add Extension Field Context / Documentation

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#169]
This is looking really great now!

V2 also requires creating an [extension context](https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#defining-and-using-custom-namespaces). Happy to do this for you, just need a quick check of the below and a response to that CNAME e-mail I sent you.

Could you quickly check the "britishcycling:" fields you've got in your code that could possibly be included in the feed (e.g. just ctrl+f for "britishcycling:" in your code would do it). I've got the list below already, but just wanted to check I hadn't missed any!

```
"britishcycling:stoppingPoints": "Best Western Rogerthorpe Manor Hotel",
"britishcycling:otherInformation": "Contact details for stopping point ops@rogerthorpemanor.co.uk",
"britishcycling:gpxFile": "https://lr-media.staging.phoenixdigital.agency/download/dc5bd2106a5a6788d40d1bd0c9846a6b",
"britishcycling:terrain": "Tarmac Road",
"britishcycling:topography": "Some Hills",
"britishcycling:publicTransport": true,
"britishcycling:publicTransportDetails": "Pontefract Train Station"
"britishcycling:routePhotos": [
  {
    "type": "ImageObject",
    "url": "https://lr-media.staging.phoenixdigital.agency/image/e02cc19c4c7a1364001b823eaa2abb37",
    "caption": ""
  }
]

etc.
```

I can also update the documentation page using this too!

**Comment by nickevansuk** [comment]
Quick question on two of these:
- I can't find examples of "attendeeInstructions" in the feed? Might be worth replacing this with the current contents of "britishcycling:otherInformation" if they don't usually fill that out? Then we remove "britishcycling:otherInformation"?
- I can't find examples of "Event.image" in the feed? Might be worth replacing these with the current contents of "britishcycling:routePhotos"  if they don't usually fill that out? Then we remove "britishcycling:routePhotos"?

**Comment by nickevansuk** [comment]
Ok so first stab at this is context here:

http://data.goskyride.com/opendata/britishcycling.jsonld

Will move it to other domain as soon as CNAME is sorted, and keen to remove the above two properties britishcycling:otherInformation and britishcycling:routePhotos if the data is better suited within standard properties?

To make this work you just need replace:

```
"@context": [
  "https://www.openactive.io/ns/oa.jsonld",
  "https://www.openactive.io/ns-beta/oa.jsonld"
],
```

with

```
"@context": [
  "https://openactive.io/",
  "https://openactive.io/ns-beta",
  "http://data.letsride.co.uk/opendata/britishcycling.jsonld"
],
```

**Comment by sevenpointsix** [comment]
This should all be in place now @nickevansuk

**Comment by nickevansuk** [comment]
Looks good, two quick things:

## Properties with null and empty strings should not be included

`caption` should not be included if null or an empty string

In this page: http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1524821428&afterId=91283
```
"image": [ {
  "type": "ImageObject",
  "url": "https://lr-media.staging.phoenixdigital.agency/image/1c980abd41131474c0c476bb33cf685b",
  "caption": null
} ]
```

## Rename "britishcycling:attendeeInstructions"

`"britishcycling:attendeeInstructions"` should be named just `"attendeeInstructions"`

**Comment by nickevansuk** [comment]
http://data.letsride.co.uk/opendata/britishcycling.jsonld has now been updated to the latest spec
