### ISSUE TITLE
Quick tweak to genderRestriction for V2

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#170]
To conform with V2 `genderRestriction` has very slightly changed:
```
"genderRestriction": "https://openactive.io/Female"
```

Updates as below (note "http**s**" and removal of "ns#"):

`"http://openactive.io/ns#Female"` -> `"https://openactive.io/Female"`
`"http://openactive.io/ns#Male"` -> `"https://openactive.io/Male"`
`"http://openactive.io/ns#None`" -> `"https://openactive.io/None"`

**Comment by sevenpointsix** [comment]
Hi @nickevansuk . I've made this change, it's not a big one, but I know that Allison at BC is very keen to draw a line under this kind of thing as ultimately she's paying for our time! Are we expecting any further changes to the spec at all? Is a V3 imminent, for example?

**Comment by nickevansuk** [comment]
Amazing, thanks! V3 is due in ~18 months or even further away, and we're not expecting further breaking changes following V2 release (due next week).

I've been trying to give all feedback to date in line with the V2 work so that British Cycling are good-to-go ahead of the Sport England push for V2 upgrade next month, just was slightly off in a couple of my predictions.

So when the validator is fixed next week you should see that you fully conform (hopefully!!)!

**Comment by nickevansuk** [comment]
Really sorry about this, the V2 spec changed again (and for the last time, it's being published today at last!).

`"https://openactive.io/Female"` -> `"https://openactive.io/FemaleOnly"`
`"https://openactive.io/Male"` ->  `"https://openactive.io/MaleOnly"` 
`"https://openactive.io/None"` -> `"https://openactive.io/NoRestriction"`

**Comment by nickevansuk** [comment]
This appears to not have been updated (https://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=53199&afterId=86568)

**Comment by nickevansuk** [comment]
Looks good!
