### ISSUE TITLE
Minor tweaks to match V2

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#172]
Version 2 of the modelling specification is about to be released, and the England Netball only requires a few tweaks to be compliant:

## Fields that now require arrays

Simply add the existing content of `activity` and `leader` to an array.

```
  "activity": [
    {
      "id": "https://openactive.io/activity-list#aba839fb-5cd2-4042-b651-c09c86bce1e2",
      "type": "Concept",
      "prefLabel": "Walking Netball",
      "inScheme": "https://openactive.io/activity-list"
    }
  ],
```

```
  "leader": [
    {
      "type": "Person",
      "name": "Liz James",
      "email": "izziescissors@hotmail.co.uk"
    }
  ],
```

```
  "level": [ "Mixed" ],
```

```
  "category": [ "Holiday camps" ],
```

```
  "category": [ "Coached Sessions" ],
```

```
  "eventSchedule": [
    {
      "type": "Schedule",
      "startDate": "2018-08-01",
      "repeatCount": 3,
      "repeatFrequency": "P1D",
      "duration": "P3D",
      "startTime": "09:00",
      "endTime": "17:00",
      "scheduledEventType": "Event"
    }
  ],
```

### logo

`"logo": "https://www.englandnetball.co.uk/app/uploads/2016/04/Walking-Netball.jpg",`

should be:

```
    "logo": {
      "type": "ImageObject",
      "url": "https://www.englandnetball.co.uk/app/uploads/2016/04/Walking-Netball.jpg"
    }
```

## Add `s` to URLs to make them `https`

Simply add `s` to the following URLs to make them `https`

"https://schema.org/EventCancelled"
"https://schema.org/EventPostponed"
"https://schema.org/EventRescheduled"
"https://schema.org/EventScheduled".

##  Rename `frequency` to `repeatFrequency`

Simply rename `frequency` to `repeatFrequency`

`"repeatFrequency": "P14D"`

## Amend openactive.io URLs in "activity"

- Remove the second "**/**" from "`id`" 
- Remove the "**/activity-list.jsonld**" from "`inScheme`"
- Remove the "**www.**" from "`id`"  and "`inScheme`"

```
"activity": {
    "id": "https://www.openactive.io/activity-list/#aba839fb-5cd2-4042-b651-c09c86bce1e2",
    "type": "Concept",
    "prefLabel": "Walking Netball",
    "inScheme": "https://www.openactive.io/activity-list/activity-list.jsonld"
  }
```

should be

```
"activity": {
      "id": "https://openactive.io/activity-list#aba839fb-5cd2-4042-b651-c09c86bce1e2",
      "type": "Concept",
      "prefLabel": "Walking Netball",
      "inScheme": "https://openactive.io/activity-list"
  }
```

## Update "@context"

```
"@context": "https://www.openactive.io/ns/oa.jsonld",
```

should be

```
  "@context": [
    "https://openactive.io/",
    "https://openactive.io/ns-beta"
  ],
```

## Rename Event to more specific types

- The outer `Event` should be renamed `ScheduledSession`
- The `Event` inside the `superEvent` property should be renamed `SessionSeries`

```
  "type": "Event",
  ...
  "superEvent": {
    "type": "Event"
    ...
  }
```

should be:

```
  "type": "ScheduledSession",
  ...
  "superEvent": {
    "type": "SessionSeries"
    ...
  }
```

## Price should always be a float
- "`price`" is now always a decimal

```
"offers": 
  {
    "type": "Offer",
    "name": "Full price cost",
    "price": 45, /* Price should always be a decimal */
    "priceCurrency": "GBP"
  }
]
```

## Time should always include leading zero

```
"startTime": "9:00",
```
should be:
```
"startTime": "09:00",
```

## For items that are NOT CourseInstances, use `PartialSchedule`

```
    "eventSchedule": {
      "type": "Schedule",
      "endDate": "2018-12-06",
      "frequency": "P7D"
    }
```

should be:

```
    "eventSchedule": {
      "type": "PartialSchedule",
      "endDate": "2018-12-06",
      "frequency": "P7D"
    }
```

**Comment by daniel-somersault** [comment]
@nickevansuk Hi Nick, I think we need to concentrate on the current version as we're already way over the time England Netball have budgeted for this implementation.

**Comment by nickevansuk** [comment]
Looks good!
