### ISSUE TITLE
V2 model conformance: moving common fields

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#174]
## SessionSeries and ScheduledSession (note: not for NYC)

To conform to the V2 model, as much data that's shared between `ScheduledSession`s should be moved in to the superEvent `SessionSeries` as possible.

This is achieved by simply taking the fields that are currently included at the main `ScheduledSession` level, and moving them as-is into the inside of the `superEvent` object.

Ideally only `identifier`, `eventStatus`, `startDate`, `endDate`, `duration` and `url` would exist at the `ScheduledSession` level, and everything else would be in the `superEvent`.

For all the records I can see, the only difference between sessions with the same `superEvent.identifier` (e.g. "WN006115") is in the fields listed above. All the other fields seem to be common to all records with the same `superEvent.identifier`? 

If that's the case then simply move everything else into the `superEvent`.

An example of an ideal record where this has been done is below:

```javascript
{
  "@context": [
    "https://openactive.io/",
    "https://openactive.io/ns-beta"
  ],
  "type": "ScheduledSession",
  "identifier": 71350,
  "superEvent": {
    "identifier": "WN006115",
    "type": "SessionSeries",
    "programme": {
      "type": "Brand",
      "name": "Walking Netball",
      "description": "Walking Netball has evolved from a growing demand for walking sports. Often, one of netball’s strengths is that people never forget playing the sport and the memories as well as the love for the game never leave.\r\n\r\nWalking Netball is a slower version of the game; it is netball, but at a walking pace. The game has been designed so that anyone can play it regardless of age or fitness level.\r\n\r\nFrom those who have dropped out of the sport they love due to serious injury, to those who believed they had hung up their netball trainers many years ago, it really is for everyone.\r\n\r\nWomen the length of the country have begun playing the game of Walking Netball for the fun, laughter and camaraderie the social session brings, as much as the health benefits on offer. It can give those who feel isolated an outlet, provide an activity for those who don’t deem themselves fit enough to run anymore and offer a stepping stone for those looking for a pathway back into netball.",
      "logo": {
        "type": "ImageObject",
        "url": "https://www.englandnetball.co.uk/app/uploads/2016/04/Walking-Netball.jpg"
      },
      "url": "https://www.englandnetball.co.uk/my-game/walking-netball/",
      "beta:video": "https://www.youtube.com/watch?v=qzQfnv7sFPg"
    },
    "name": "Walking Netball",
    "description": "Walking Netball has evolved from a growing demand for walking sports. Often, one of netball’s strengths is that people never forget playing the sport and the memories as well as the love for the game never leave.\r\n\r\nWalking Netball is a slower version of the game; it is netball, but at a walking pace. The game has been designed so that anyone can play it regardless of age or fitness level.\r\n\r\nFrom those who have dropped out of the sport they love due to serious injury, to those who believed they had hung up their netball trainers many years ago, it really is for everyone.\r\n\r\nWomen the length of the country have begun playing the game of Walking Netball for the fun, laughter and camaraderie the social session brings, as much as the health benefits on offer. It can give those who feel isolated an outlet, provide an activity for those who don’t deem themselves fit enough to run anymore and offer a stepping stone for those looking for a pathway back into netball.",
    "activity": [
      {
        "id": "https://openactive.io/activity-list#aba839fb-5cd2-4042-b651-c09c86bce1e2",
        "type": "Concept",
        "prefLabel": "Walking Netball",
        "inScheme": "https://openactive.io/activity-list"
      }
    ],
    "category": [
      "Coached Sessions"
    ],
    "level": [
      "Beginner"
    ],
    "eventSchedule": [
      {
        "type": "PartialSchedule",
        "endDate": "2018-10-30",
        "repeatFrequency": "P14D"
      }
    ],
    "organizer": {
      "type": "Organization",
      "name": "England Netball",
      "url": "https://www.englandnetball.co.uk",
      "sameAs": [
        "https://www.facebook.com/southdurhamandclevelandnetball/",
        "https://twitter.com/NetballInSDandC"
      ]
    },
    "location": {
      "type": "Place",
      "name": "Thornaby Pavillion",
      "address": {
        "type": "PostalAddress",
        "streetAddress": ", Chiswick",
        "addressLocality": "London ",
        "addressRegion": "Middlesex",
        "postalCode": "W4 1RZ",
        "addressCountry": "GB"
      },
      "geo": {
        "type": "GeoCoordinates",
        "latitude": 54.5386474,
        "longitude": -1.290952
      }
    },
    "offers": [
      {
        "type": "Offer",
        "name": "Full price cost",
        "price": 3.5,
        "priceCurrency": "GBP"
      }
    ],
    "leader": [
      {
        "type": "Person",
        "name": "Liz James",
        "email": "izziescissors@hotmail.co.uk"
      }
    ]
  },
  "eventStatus": "https://schema.org/EventScheduled",
  "startDate": "2018-09-11T11:00:00Z",
  "endDate": "2018-09-11T12:00:00Z",
  "duration": "PT1H",
  "url": "https://www.englandnetball.co.uk/?pagename=session&sessionid=[71350&WN006115"
}
```

## Course and CourseInstance (NYC only)

Note that Course and CourseInstance follows a different structure to SessionSeries and ScheduledSession.

Conformance for `Course` and `CourseInstance` can be achieved more simply from the current structure, by simply:
- Updating `programme` property to `course`
- Updating `Brand` type to `Course`
- Duplicating `"activity"` into `Course`
- Duplicating `organizer` into `Course` as `author`

Also rename the Course from "NYC" to "Netball Youth Camp", as it will not be clear what NYC is to most users.

```javascript
{
  "@context": [ "https://openactive.io/" , "https://openactive.io/ns-beta" ],
  "type": "CourseInstance",
  "identifier": 76121,
  "beta:course": { /* update to "course" */
    "type": "Course", /* update to "Course" */
    "name": "Netball Youth Camp", /* update to "Netball Youth Camp" */
    "description": "Netball Youth Camps give junior netballers the chance to get together with their friends and take to the court in the holidays!\r\n\r\nThe camp is a non-residential holiday camp providing ‘Nothing but Netball’; not only will there be top quality coaching and fun netball activities but there is even an opportunity to meet and be inspired by an elite player.\r\n\r\nIf you are a junior netball lover (or the parent of one!) these are an unmissable holiday activity.",
    "logo": {
      "type": "ImageObject",
      "url": "https://www.englandnetball.co.uk/app/uploads/2016/03/Netball-youth-camp-ball.jpg"
    },
    "url": "https://www.englandnetball.co.uk/NYC",
    "beta:video": "https://www.youtube.com/watch?v=lvlEpaKTotQ",
    "activity": [ /* Duplicating into Course */
      {
        "id": "https://openactive.io/activity-list#fbdc35a8-3dd0-40ee-a7ca-6ff40b3e5f90",
        "type": "Concept",
        "prefLabel": "Netball",
        "inScheme": "https://openactive.io/activity-list"
      }
    ],
    "author": {  /* add this with same info as used in organizer below */
      "type": "Organization",
      "name": "England Netball",
      "url": "https://www.englandnetball.co.uk"
    }
  },

  "category": [ "Holiday camps" ],
  "level": [ "Mixed" ],

  "name": "Netball Youth Camp",
  "startDate": "2018-08-01", 
  "endDate": "2018-08-04", 
  "duration": "P4D",
  "eventSchedule": [
    {
      "type": "Schedule",
      "startDate": "2018-08-01",
      "endDate": "2018-08-04",
      "repeatCount": 4,
      "repeatFrequency": "P1D",
      "startTime": "09:00",
      "endTime": "17:00",
      "duration": "PT8H",
      "scheduledEventType": "Event"
    }
  ],
  "eventStatus": "https://schema.org/EventScheduled",
  "activity": [
    {
      "id": "https://openactive.io/activity-list#fbdc35a8-3dd0-40ee-a7ca-6ff40b3e5f90",
      "type": "Concept",
      "prefLabel": "Netball",
      "inScheme": "https://openactive.io/activity-list"
    }
  ],
  "location": {
    "type": "Place",
    "name": "Trent College and The Elms",
    "address": {
      "type": "PostalAddress",
      "streetAddress": ", Long Eaton",
      "addressLocality": "Nottingham",
      "addressRegion": "Nottinghamshire",
      "postalCode": "NG10 4AD",
      "addressCountry": "GB"
    },
    "geo": {
      "type": "GeoCoordinates",
      "latitude": 52.901455,
      "longitude": -1.282734
    }
  },

  "ageRange": {
    "type": "QuantitativeValue",
    "minValue": 11,
    "maxValue": 16
  },
  "leader": [ {
    "type": "Person",
    "jobTitle": "Derbyshire and Nottinghamshire NDO",
    "name": "Rachel Gregg",
    "email": "rachel.gregg@englandnetball.co.uk"
  } ],
  "organizer": {
    "type": "Organization",
    "name": "England Netball",
    "url": "https://www.englandnetball.co.uk",
    "sameAs": [
      "https://www.facebook.com/southdurhamandclevelandnetball/",
      "https://twitter.com/NetballInSDandC"
    ]
  },
  "url": "https://www.englandnetball.co.uk/?pagename=session&sessionid=[76121&NYC006506",
  "offers": [
    {
      "type": "Offer",
      "name": "Member cost",
      "price": 124,
      "priceCurrency": "GBP"
    },
    {
      "type": "Offer",
      "name": "Non-member cost",
      "price": 154,
      "priceCurrency": "GBP"
    }
  ]
}
```

**Comment by nickevansuk** [comment]
You can use this to help: https://validator.openactive.io/?url=https%3A%2F%2Fapi.englandnetball.co.uk%2Fapi%2Fopenactive%2Fsessions&version=2.0

**Comment by daniel-somersault** [comment]
@nickevansuk are we able to sign off against v1?  We're already well over in terms of time that was estimated for implementing this so will delay it even further if I need to go back for additional budget sign off.

**Comment by nickevansuk** [comment]
Hi @daniel-somersault unfortunately not as v1 is now deprecated, had a quick chat with Chris at EN on Friday about this though so she's aware there are just two left. Hopefully these will be much quicker as they're more about minor tweaks to content and you have the validator to aid QA now too!

**Comment by daniel-somersault** [comment]
@nickevansuk Hi Nick - ok, thanks for confirming.  Is anything likely to change or is everything now set in v2?

**Comment by nickevansuk** [comment]
That's right @daniel-somersault, all set. It's not likely to change for a while now. The examples above are fully compliant, and should be achievable by moving properties around and formatting them as per the above and https://github.com/openactive/activation/issues/172.

Note if you paste the examples above into the validator you'll see an error caused by a requirement for a URL for SessionSeries - although this is a required field you don't have anything like this for EN, so you can ignore this.

My recommendation here would be to follow the instructions in https://github.com/openactive/activation/issues/172 and here, and then to check these two pages in the validator:

- https://validator.openactive.io/?url=https://api.englandnetball.co.uk/api/openactive/sessions?afterId=76120&afterTimestamp=0 (the top result is NYC)

- https://validator.openactive.io/?url=https://api.englandnetball.co.uk/api/openactive/sessions?afterId=77714&afterTimestamp=1536692601 (Back to Netball)

One thing I've also noticed is that there are some things in the feed without offers (e.g. "UNO" ID 77751 and "Walking Netball" ID 78315), and the URLs for these seem to point to empty pages. `offers` is required, but can contain an `Offer` set to `"price": 0` for free activities. Are these items invalid and should they be filtered out?

**Comment by daniel-somersault** [comment]
@nickevansuk Hi Nick, we have got the api to a point where it is now validating against V2 apart from one item, the url for the programme (SessionSeries).  There is no destination for this currently, they only have the individual session url on the England Netball so we have nothing that we put in for this.  Can you advise?

For your note on sessions without offers, I expect that the information has just not been populated by EN staff.  They now have an approval process for programmes before they will appear in the api feed so this shouldn't really happen.  UNO has also been removed - it shouldn't be in the feed.

**Comment by nickevansuk** [comment]
Thanks @daniel-somersault this looks really great. Couple of errors still for NYC:

https://validator.openactive.io/?url=https%3A%2F%2Fapi.englandnetball.co.uk%2Fapi%2Fopenactive%2Fsessions%3FafterId%3D76120%26afterTimestamp%3D0&version=2.0

"activity" needs to be duplicated across the CourseInstance and the Course, and `eventSchedule` must be an array (see the validator for details on these errors, see the above example which shows this).

Regarding the url: As I mentioned in the second para of https://github.com/openactive/activation/issues/174#issuecomment-432219779 above, there's nothing like this in EN right now so you can ignore this. It would be great to have a page for the EventSeries if there was ever a redesign of the site, as it would create a better user experience, but as the ScheduledSession URLs are provided data users will still be able to use those.

**Comment by daniel-somersault** [comment]
Tanks @nickevansuk, must have missed that part.  The NYC errors have been fixed so it is just the url that doesn't validate.  Are we there?

**Comment by nickevansuk** [comment]
Hello @daniel-somersault this is really great news! One final thing that should take a couple of seconds to fix: we should actually use `"ScheduledSession.SessionSeries"` as the kind instead of `"SessionSeries.ScheduledSession"`

To save you some time I've updated your dataset site to reflect that you are now fully conformant, and created a PR here to update your docs too: https://github.com/england-netball/opendata/pull/1

If you're happy with all of that just merge the PR and we'll get in touch with Chris to arrange launch comms :)

Well done for getting this over the line!!!

**Comment by daniel-somersault** [comment]
Hi @nickevansuk - fantastic news.  We have just pushed the modification for "ScheduledSession.SessionSeries".  I'll take a look at the dataset site and PR and do what I need to, if anything.  
Thanks, Daniel

**Comment by nickevansuk** [comment]
Wonderful @daniel-somersault ! I'll go ahead and close all these issues, and look out for the updated dataset site readme!
