### ISSUE TITLE
RPDE implementation issue

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#175]
Paging does not seem to be correctly implemented: `id` and `modified` values of the last item in the page do not match those in the `next` URL. The last item in each page must be used to generate the `next` URL. 

One symptom of this is that the following page erroneously points to itself: https://api.englandnetball.co.uk/api/openactive/sessions?afterId=77708&afterTimestamp=1536663982

**Comment by nickevansuk** [comment]
Also note the page size should be 500 rather than 20.

**Comment by nickevansuk** [comment]
Please use the validator at https://validator.openactive.io/rpde with the following seed URL to see the issue:
- https://api.englandnetball.co.uk/api/openactive/sessions?afterId=77708&afterTimestamp=1536663982

Also please see our handy video to explain why this is problematic: https://developer.openactive.io/publishing-data/data-feeds/how-a-data-feed-works

**Comment by daniel-somersault** [comment]
@nickevansuk it seems to be passing now on the validator

**Comment by nickevansuk** [comment]
@daniel-somersault seems to still be failing for me:

https://validator.openactive.io/rpde?url=https://api.englandnetball.co.uk/api/openactive/sessions?afterId=77708&afterTimestamp=1536663982

**Comment by daniel-somersault** [comment]
@nickevansuk I'm a bit confused, if I run the validator without any parameters set everything passes?

**Comment by nickevansuk** [comment]
The validator only checks 20 pages of the feed from the start point provided. Starting from a point further into the feed sometimes reveals issues not seen at the beginning of the feed.

Suggest checking the video and query on this page to ensure your implementation is correct:

https://developer.openactive.io/publishing-data/data-feeds/how-a-data-feed-works

**Comment by daniel-somersault** [comment]
@nickevansuk hopefully we have fixed the problem now.  Passing against that now.

**Comment by nickevansuk** [comment]
Looks great!
