### ISSUE TITLE
Activity spot check

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#176]
Just did a spot check of `"activity"` too, which seems to not be pulling through mountain biking (as per original spec: https://github.com/openactive/activation/issues/104)

Suggest this rule:
- If bike type includes "Road" or "All bike types", then use the activity "`Road Cycling`". Otherwise if bike type includes only one or both of "Mountain Bike" or "Hybrid (off road tyres)" (and no other types), then use the activity "`Mountain biking`". Otherwise use "`Recreational Cycling`".

Also ensure the IDs match in each case as follows:
```
    "id": "https://openactive.io/activity-list#2a41c553-84be-4970-b3d0-42f9ef6bd9a4",
    "prefLabel": "Road Cycling",
```

```
    "id": "https://openactive.io/activity-list#8302ec84-3d0b-44cb-b622-254596d37086",
    "prefLabel": "Mountain Biking",
```

```
    "id": "https://openactive.io/activity-list#be4762de-b26c-4bd2-bcf2-4e54b58e7830",
    "prefLabel": "Recreational Cycling",
```

# Spot check
http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=52698&afterId=3549

## https://www.letsride.co.uk/rides/le-sportif-ladies-who-ride-2

Website: `Road`
Feed:
```
"activity": [
  {
    "id": "https://openactive.io/activity-list#2a41c553-84be-4970-b3d0-42f9ef6bd9a4",
    "prefLabel": "Road Cycling",
    "type": "Concept",
    "inScheme": "https://openactive.io/activity-list"
  }
],
```
**PASS**

## https://www.letsride.co.uk/rides/grinton-breakfast-run

Website: `Mountain bike`
Feed:
```
"activity": [
  {
    "id": "https://openactive.io/activity-list#8302ec84-3d0b-44cb-b622-254596d37086",
    "prefLabel": "Mountain Biking",
    "type": "Concept",
    "inScheme": "https://openactive.io/activity-list"
  }
],
```
**PASS**

## https://www.letsride.co.uk/rides/tuesday-afternoon-social-ride

Website: `Mountain Bike`, `Hybrid (off road tyres)`, `Hybrid (road tyres)`
Feed:
```
"activity": [
  {
    "id": "https://openactive.io/activity-list#8302ec84-3d0b-44cb-b622-254596d37086",
    "prefLabel": "Mountain Biking",
    "type": "Concept",
    "inScheme": "https://openactive.io/activity-list"
  }
],
```
**FAIL**
should be
```
"activity": [
  {
    "id": "https://openactive.io/activity-list#be4762de-b26c-4bd2-bcf2-4e54b58e7830",
    "prefLabel": "Recreational Cycling",
    "type": "Concept",
    "inScheme": "https://openactive.io/activity-list"
  }
],
```

## https://www.letsride.co.uk/rides/breeze-solihull-pretty-packwood-5

Website: `All bike types`
Feed:
```
"activity": [
  {
    "id": "https://openactive.io/activity-list#2a41c553-84be-4970-b3d0-42f9ef6bd9a4",
    "prefLabel": "Road Cycling",
    "type": "Concept",
    "inScheme": "https://openactive.io/activity-list"
  }
],
```
**PASS**

## https://www.letsride.co.uk/rides/fourteen-locks-to-cwmcarn-forest-drive-6

Website: `Mountain Bike`, `Hybrid (off road tyres)`, `Hybrid (road tyres)`
Feed:
```
"activity": [
  {
    "id": "https://openactive.io/activity-list#8302ec84-3d0b-44cb-b622-254596d37086",
    "prefLabel": "Mountain Biking",
    "type": "Concept",
    "inScheme": "https://openactive.io/activity-list"
  }
],
```
**FAIL**
should be
```
"activity": [
  {
    "id": "https://openactive.io/activity-list#be4762de-b26c-4bd2-bcf2-4e54b58e7830",
    "prefLabel": "Recreational Cycling",
    "type": "Concept",
    "inScheme": "https://openactive.io/activity-list"
  }
],
```

**Comment by nickevansuk** [comment]
Looks better but still one fail on the test above

**Comment by sevenpointsix** [comment]
I don't understand why this is a fail @nickevansuk . 'If ride_level does not include "Road" or "All bike types", then use the activity "Mountain biking", otherwise use "Road Cycling".'

The "breeze-solihull-pretty-packwood-5" ride has a bike type of "All bike types", but your report states that it should be listed as a "Mountain Bike" ride...? Does this not contradict the criteria above?

**Comment by nickevansuk** [comment]
So sorry @sevenpointsix, the examples in the report were the wrong way around. The feed currently lists it as "Mountain biking", as you say it should be "Road Cycling". I've updated the report now.

Still a fail i'm afraid, but with the right data examples this time!

**Comment by sevenpointsix** [comment]
Hi @nickevansuk . Sorry this has been back and forth a bit, could you possibly check this again now?

**Comment by nickevansuk** [comment]
Actually on reflection @sevenpointsix, let me raise this with Cazz to make sure everyone is on the same page before we finalise what the rule is - just to make sure this is what she’d also expect.

This is the last one but worth getting it right!

**Comment by nickevansuk** [comment]
@sevenpointsix sorry for the delay, we've now got confirmation from British Cycling that they'd like to use "Recreational Cycling" as the new activity name and ID. I've updated all of the above to reflect this, so hopefully that should all be clear?

Very close now!!

**Comment by sevenpointsix** [comment]
@nickevansuk This should be ready for a final test on staging now.

**Comment by nickevansuk** [comment]
@sevenpointsix the two "FAIL"s in the results above are the same as they were? I've added "(and no other types)" to the rule for clarity:

- If bike type includes "Road" or "All bike types", then use the activity "Road Cycling". Otherwise if bike type includes only one or both of "Mountain Bike" or "Hybrid (off road tyres)" (and no other types), then use the activity "Mountain biking". Otherwise use "Recreational Cycling".

**Comment by sevenpointsix** [comment]
I think this is right now @nickevansuk ?

**Comment by nickevansuk** [comment]
🎉🎉🎉🎉🎉
🥳🥳🥳🥳🥳

Great job, looks like we're done!!
