### ISSUE TITLE
Images spot check

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#178]
Note that since we merged route images and primary image we've lost the primary image. The primary image from the top left of the page should be the first image in the `image` array.

## Spot check
http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=0&afterId=121250

The following rides both have a primary image, but that image is not present in the "`image`" array. The primary image should be the first image in the array.
- https://www.letsride.co.uk/rides/lakeside-canalside-riverside-5
- https://www.letsride.co.uk/rides/fast-and-furious-13

**FAIL**

This ride has one route image, and a primary image. Only the route image is included in the "`image`" array. The primary image should be the first image in the array, before the route images.
- https://www.letsride.co.uk/rides/wollaton-hall-batman-circular-3

**FAIL**

**Comment by nickevansuk** [comment]
Still failing... no changes seem to have been made relating to this? Do I have the right URL?

http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=0&afterId=121250

**Comment by sevenpointsix** [comment]
@nickevansuk I don't believe that this feedback is accurate. The https://www.letsride.co.uk/rides/lakeside-canalside-riverside-5 doesn't have an image (apart from the placeholder image top-left, but this is a generic image). We're only including in the data feed images that have actually been uploaded by the user. Do you not feel that this is the correct approach?

**Comment by nickevansuk** [comment]
Ah right that explains it. In that case the first image in the images array should be the placeholder image (or whatever is in the top-left), with the rest of the route images following that in the images array - to ensure the data matches the letsride.co.uk website.

**Comment by sevenpointsix** [comment]
I believe this should be fixed now @nickevansuk , let me know what you think?

**Comment by nickevansuk** [comment]
Nearly... they need to all be `ImageObject`s... so 

Not like this:

```
"image": [
  "https://lr-media.staging.phoenixdigital.agency/image/477bf493f793d9cdaa87c31ef54c4d3b",
  {
    "type": "ImageObject",
    "url": "https://lr-media.staging.phoenixdigital.agency/image/17eaa5144523546303dc25a3325ffe65"
  }
],
```

Like this:

```
"image": [
  {
    "type": "ImageObject",
    "url": "https://lr-media.staging.phoenixdigital.agency/image/477bf493f793d9cdaa87c31ef54c4d3b"
  },
  {
    "type": "ImageObject",
    "url": "https://lr-media.staging.phoenixdigital.agency/image/17eaa5144523546303dc25a3325ffe65"
  }
],
```

**Comment by sevenpointsix** [comment]
Good spot @nickevansuk ! This should be working as expected now.

**Comment by nickevansuk** [comment]
Fantastic, looks good!
