### ISSUE TITLE
URL spot check

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#179]
Some URLs do not seem to be valid. Is this because rides exist in staging that are not present in the live system?

## Spot check

http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=0&afterId=121700

Ride appears to be deleted or hidden (404) but is not marked as deleted in the feed:
- https://www.letsride.co.uk/rides/test-accred-route-pre-ride-br
- https://www.letsride.co.uk/rides/test-breeze-3-1
- https://www.letsride.co.uk/rides/testing-tommys-issue
- https://www.letsride.co.uk/rides/sngfnr

**Comment by sevenpointsix** [comment]
Yes @nickevansuk , this will almost certainly be due to discrepancies between the staging site and the live database.

**Comment by nickevansuk** [comment]
Ok great no worries
