### ISSUE TITLE
Next URL should be URL encoded

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#18]
`/getHappenings?afterTimestamp=2015-01-13 16:56:14 UTC&afterID=14`

should be

`/getHappenings?afterTimestamp=2015-01-13%2016:56:14%20UTC&afterID=14`

Also raised as: https://github.com/openactive/realtime-paged-data-exchange/issues/33

**Comment by manzan46** [comment]
Well spotted just fixed this one

**Comment by nickevansuk** [comment]
Great, looks good!
