### ISSUE TITLE
isAccessibleForFree must be accurate

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#189]
## Issue
The test event does not appear to be free, and yet `isAccessibleForFree` is set to true. This should only be free for events that are actually accessible for free.

**Comment by dolkensp** [comment]
Internal note: We need to exclude "Member" offers from the "free" detection

**Comment by nickevansuk** [comment]
Looks good, though needs more data to test properly

**Comment by nickevansuk** [comment]
Will leave this in QA until this goes live, in order to test properly

**Comment by nickevansuk** [comment]
Now there's more data in test, can do here. Looks good!
