### ISSUE TITLE
Add license to data

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#19]
Please also add a `license` to each page as follows:
```
{
  "next": "/prod/getSessions?afterTimestamp=2016-05-23T15:42:05.568Z&afterID=2055",
  "items": [
    {
      ...
    }
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
```

Have raised an issue to add this to the main spec: https://github.com/openactive/realtime-paged-data-exchange/issues/34

**Comment by manzan46** [comment]
Added, also added back the photos and more info about the run  and  https://www.goodgym.org//getHappenings?afterTimestamp=2016-07-4%2017:46:49%20UTC&afterID=2139

**Comment by nickevansuk** [comment]
Fantastic, thanks!
