### ISSUE TITLE
Include "Wheelchair route" in the data

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#190]
## Issue
- Include "Wheelchair route" in the data via "Physical impairment" `accessibilitySupport`.
- Use the beta property `beta:isWheelchairAccessible` proposed by EMD UK, for routes that are "Wheelchair route". 
- Use `accessibilityInformation` to indicate exact information, comma separate with "Guided route". So e.g. values would be `Guided route, Wheelchair route.` or `Guided route.` or `Wheelchair route.`.

## Example

Like this:

```javascript
{
  "@context": "https://openactive.io/",
  "type": "SessionSeries",
  "beta:isWheelchairAccessible": true,
  "accessibilitySupport": [
    {
      "type": "Concept",
      "id": "https://openactive.io/accessibility-support#dd026873-6713-4ea1-af5a-08901f651d98",
      "prefLabel": "Physical impairment",
      "inScheme": "https://openactive.io/accessibility-support"
    }
  ],
  "accessibilityInformation": "Guided route, Wheelchair route."
}
```

**Comment by dolkensp** [comment]
We don't have this data in our system.
