### ISSUE TITLE
Include "Guided route" in the data

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#191]
## Issue
- Include "Guided route" in the data via "Physical impairment" accessibilitySupport.
- Use `accessibilityInformation` to indicate exact information, comma separate with "Guided route". So e.g. values would be `Guided route, Wheelchair route.` or `Guided route.` or `Wheelchair route.`.

## Example

Like this:

```javascript
{
  "@context": "https://openactive.io/",
  "type": "SessionSeries",
  "accessibilitySupport": [
    {
      "type": "Concept",
      "id": "https://openactive.io/accessibility-support#1393f2dc-3fcc-4be9-a99f-f1e51f5ad277",
      "prefLabel": "Visual impairment",
      "inScheme": "https://openactive.io/accessibility-support"
    }
  ],
  "accessibilityInformation": "Guided route, Wheelchair route."
}
```

**Comment by dolkensp** [comment]
We don't have this data in our system
