### ISSUE TITLE
Ping! Example

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#21]
```
{
  "items": [
    {
      "id": "861",
      "kind": "table_tennis_table_location",
      "modified": 1468235306,
      "state": "updated",
      "data": {
        "lat": "53.5372727",
        "lng": "-1.4486005",
        "name": "5ives Community Sports Club",
        "address": "Burnsall Grove, Barnsley",
        "county": "",
        "country": "uk",
        "postcode": "S70 3JR",
        "tel": "no"
      }
    }
  ]
}
```

**Comment by nickcw123** [comment]
{
            "id": "53",
            "kind": "table_tennis_table_location",
            "modified": "1468429656",
            "state": "updated",
            "data": {
                "lat": "53.3941825",
                "lng": "-2.9810493",
                "name": "Camp & Furnace",
                "address": "67 Greenland Sreet,Liverpool",
                "county": "",
                "country": "uk",
                "postcode": "L1 OBY",
                "tel": "yes",
                "indoor_outdoor": "Indoor",
                "static": "Rollaway"
            }
        },
