### ISSUE TITLE
Include `schedulingNote`

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#219]
## Issue
Include `schedulingNote`

## Example

```javascript
{
  "@context": "https://openactive.io/",
  "type": "SessionSeries",
  "schedulingNote": "Sessions are not running during school holidays."
}
```

**Comment by jontolton** [comment]
Not sure what is supposed to go in here - we don't really have anything appropriate except the class description, which is already going into the Description property.

**Comment by nickevansuk** [comment]
@vakeesan26 I understand this is still in scope for EMD?

**Comment by vakeesan26** [comment]
"**When does this class run?**" field mapped now
if value is empty then it will be removed.

**Comment by nickevansuk** [comment]
Great!
