### ISSUE TITLE
Missing paging

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#22]
The example looks good, but the endpoint is lacking paging - there is no "next" URL.

**Comment by nickcw123** [comment]
I could not see what to set the next url to if there is no paging. The data amount is too small to need paging?

**Comment by nickevansuk** [comment]
Ah I see, so paging is a requirement for the standard, but is super simple to implement. See [4.3.1](https://www.openactive.io/realtime-paged-data-exchange/#modified-timestamp-and-id). Pseudocode for the query below:
```
   var query;
   if (queryParams.afterTimestamp || queryParams.afterId) {
       query = Session.query().filter((Session.modified == queryParams.afterTimestamp && Session.id > queryParams.afterId) || (Session.modified > queryParams.afterTimestamp));
   } else {
       query = Session.query()
   }
   return query.sort([Session.modified, Session.id])
```

Please do paste whatever code you end up with if it's in one place and we'll include it in the next version of the standard as a PHP example.

**Comment by nickcw123** [comment]
Ok I have added the next url.
The next url returns no items until one of them is updated. and then it returns the updated item.

I think thats what you want.

**Comment by nickevansuk** [comment]
Nearly there, just to be really clear:

![image](https://cloud.githubusercontent.com/assets/2616208/16815334/52f28294-4931-11e6-884f-2f81d68e8316.png)

The numbers in red (i.e. the last modified and ID in the page) should be the ones used in the next URL for the page, unless there are no items on the page, in which case the next URL be recreated from the page's own URL parameters.

This will be clarified in the next version of the spec (https://github.com/openactive/realtime-paged-data-exchange/issues/29)

**Comment by nickcw123** [comment]
Ok that should be sorted now.

**Comment by nickevansuk** [comment]
You might want to check the logic matches the below:

```
(Session.modified == queryParams.afterTimestamp && Session.id > queryParams.afterId) || (Session.modified > queryParams.afterTimestamp)
```

Going to http://www.pingengland.co.uk/realtime.php?afterTimestamp=1468429653&afterId=973 should return lots of records (as the timestamp is just before that on most of the records).

**Comment by nickcw123** [comment]
Ok. So when comparing IDs the time stamps must equal. This makes more sense now, I did wonder why 2 variables were being used. I will update this later on.

**Comment by nickcw123** [comment]
ok this should be sorted.

**Comment by nickevansuk** [comment]
Doesn't appear to be, http://www.pingengland.co.uk/realtime.php?afterTimestamp=1468429656&afterId=974 seems to contain the "next" page which has the same content?

**Comment by nickcw123** [comment]
Ok it should be now. Seems the sql server and the php servers had different time zones set, causing havoc.

**Comment by nickevansuk** [comment]
Excellent, looks good!
