### ISSUE TITLE
Personal data exposed without permission

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#223]
## Issue
When "Show my contact details on the website?" is "No", the details are still included in the feed.

The form reads: "`Choosing 'yes' will share your contact details on the EMD UK class search. Choosing 'no' will share organisation contact details only.`"

![screenshot 2019-01-09 at 22 10 54](https://user-images.githubusercontent.com/2616208/50931824-ac7d8f00-145b-11e9-8683-1f3c68b4b699.png)

## Solution

Only when `Show my contact details on the website` is `no`: "leader" field must NOT be included in either feed, and organisation details must be included in `organizer` field instead:

## Example

Only when `Show my contact details on the website` is `no`

Not like this:

```javascript
  "organizer": {
    "name": "Mr Nick Evans",
    "identifier": 199094,
    "type": "Person",
    "url": "https://portal.emduk.org/find-an-instructor/199094"
  },
  "leader": [
    {
      "name": "Mr Nick Evans",
      "gender": "https://schema.org/Male",
      "identifier": 199094,
      "type": "Person"
    }
  ]
```

Like this:

```javascript
  "organizer": {
    "type": "Organization",
    "identifier": 199094,
    "name": "Open Data Institute",
    "email": "hello@openactive.io",
    "telephone": "+442035989395",
    "url": "http://www.OpenActive.io"
  }
```

**Comment by nickevansuk** [comment]
Leader seems to be broken for:

![screenshot 2019-01-30 at 18 49 01](https://user-images.githubusercontent.com/2616208/52004736-bf660b00-24bf-11e9-8644-c56df03569b1.png)

It's now coming through as a website URL instead of the `leader` object!

**Comment by nickevansuk** [comment]
And for this the URL for the Leader is being set to the class listing URL which is hidden on the input form, so this should be hidden.

![screenshot 2019-01-30 at 18 51 57](https://user-images.githubusercontent.com/2616208/52004888-34d1db80-24c0-11e9-9964-f1099fa40e68.png)

![screenshot 2019-01-30 at 18 51 52](https://user-images.githubusercontent.com/2616208/52004900-3ac7bc80-24c0-11e9-9244-dbaa2a6cb775.png)


The telephone number is also being rendered as an integer rather than a string

**Comment by vakeesan26** [comment]
telephone is now string

**Comment by nickevansuk** [comment]
If I input a telephone number of "+442035989395" it appears in the feed as "442035989395"

**Comment by vakeesan26** [comment]
phone number issue fixed !
