### ISSUE TITLE
Evidence of deleted flag

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#23]
No evidence of a deleted flag, any deleted records should be marked as deleted in your database (instead of the row actually being deleted), so that it can be reflected in the feed

**Comment by nickcw123** [comment]
Can you explain a bit more what you mean here.

Items that have been deleted appear as follows...

        {
            "id": "166",
            "kind": "table_tennis_table_location",
            "modified": 1468423373,
            "state": "deleted"
        },

**Comment by nickevansuk** [comment]
Ah brilliant, must have missed that before... looks great!
