### ISSUE TITLE
Please add a license 

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#24]
It is recommended that at a minimum you add a license key as follows: `"license": "https://creativecommons.org/licenses/by/4.0/"`

For example:
```
{
  "next": "...",
  "items": [
    {
      "id": "861",
      "kind": "table_tennis_table_location",
      "modified": 1468235306,
      "state": "updated",
      "data": {
        "lat": "53.5372727",
        "lng": "-1.4486005",
        "name": "5ives Community Sports Club",
        "address": "Burnsall Grove, Barnsley",
        "county": "",
        "country": "uk",
        "postcode": "S70 3JR",
        "tel": "no"
      }
    }
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
```

This is due to be incorporated into the next version of the standard. See (https://github.com/openactive/realtime-paged-data-exchange/issues/34).

**Comment by nickcw123** [comment]
What license should I use?

**Comment by nickevansuk** [comment]
The one above is recommended. Use "https://creativecommons.org/licenses/by/4.0/".

**Comment by nickcw123** [comment]
I have added the license as specified.

**Comment by nickevansuk** [comment]
Perfect
