### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#25]
The following fields / example values from the Ping! website were not found in the data:

- Outdoor
- Static

Please ensure as much data as is available is provided.

**Comment by nickcw123** [comment]
Added these fields.
Will add to the doc.

**Comment by nickevansuk** [comment]
Great, thanks - check https://github.com/table-tennis-england to accept your invitation and you'll be able to edit the doc yourself directly on https://github.com/table-tennis-england/opendata/blob/master/README.md

**Comment by nickcw123** [comment]
Should be done.

**Comment by nickevansuk** [comment]
Can you see this reflected in https://github.com/table-tennis-england/opendata/blob/master/README.md? Can't see it here? Which page did you change?

**Comment by nickcw123** [comment]
This should be done now.

**Comment by nickevansuk** [comment]
Fantastic, could you provide a list of available values for `indoor_outdoor` and `static`, or are they free text?

**Comment by nickcw123** [comment]
They are free text.

**Comment by nickevansuk** [comment]
Perfect, thanks! Great work - looks like we're there!

Thanks for all your help.
