### ISSUE TITLE
Update documentation - missing field

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#26]
The field "tel" is not currently described in the documentation.

Please respond here with your Github username, and I'll add you to the organisation to update the documentation according.

Documentation: https://github.com/table-tennis-england/opendata/

**Comment by nickevansuk** [comment]
@nickcw123 I've added you to the table-tennis-england repo

**Comment by nickcw123** [comment]
Needs the following adding...

tel= Gives details of the telephone of the person who looks after the table.
indoor_outdoor = Gives details of weather the table tennis table is indoors or out doors.
static = Gives details of weather the table tennis table is fixed or fold away.

**Comment by nickevansuk** [comment]
Great, thanks - check https://github.com/table-tennis-england to accept your invitation and you'll be able to edit the doc yourself directly on https://github.com/table-tennis-england/opendata/blob/master/README.md

**Comment by nickcw123** [comment]
Not 100% sure but i think i have now done this. not used git before.

**Comment by nickevansuk** [comment]
If you accept the invitation to GitHub at  https://github.com/table-tennis-england (the message at the top of the screen), then go to https://github.com/table-tennis-england/opendata/blob/master/README.md and press the edit button, you can do it all from the GUI (it's Markdown syntax). You shouldn't need to use git directly.

**Comment by nickcw123** [comment]
Humm I did that. I have just done it again. I think its branching it. I can see both my edits now but not on the main line. They are on forks.

**Comment by nickevansuk** [comment]
You haven't accepted the invite at https://github.com/table-tennis-england I'm afraid.

See the top of the screen for the invite. When you've accepted it, you'll be able to edit everything. Until then you'd have to fork and pull request (which is a bit more complicated):

![githubviewinvitation](https://cloud.githubusercontent.com/assets/2616208/16849488/8537f164-49f2-11e6-9f75-c7fd76722a20.png)

**Comment by nickcw123** [comment]
This should be done now.

**Comment by nickevansuk** [comment]
Great, can see you're a member, glad you have access now
