### ISSUE TITLE
"modified": 1467030449 was great

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#32]
In your previous examples you had e.g.
```
"modified": 1467030449,
```

This was perfect. Not sure if got our wires crossed in conversation, could we revert to this?

That will allow the endpoint to pass in the validator: http://validator.openactive.io/

**Comment by TheLegendOfProgramming** [comment]
I saw that there were other examples with the dateTime, and i thought that would be easier for everyone, and more readable, but we definetly can, no problem.

**Comment by nickevansuk** [comment]
Great, comment back when you've fixed and I'll take a look then close the issue accordingly

**Comment by TheLegendOfProgramming** [comment]
Just to make sure, should it be only for the modified or for the URL too?

**Comment by nickevansuk** [comment]
Both would be great to keep it consistent

**Comment by TheLegendOfProgramming** [comment]
Okay, everything is set beside the Dataset Site, i have to consult with my boss and well do it a bit later today. Test it and tell me if there is anything to add :)

**Comment by nickevansuk** [comment]
For this issue: looks good. It's usually good practice to respond in each issue to say you've tackled it.

Great work moving this forward, still a couple of issues left (check https://github.com/openactive/activation/milestone/13). Spoke with Mattias today and he seemed ok with the Dataset Site, so hopefully you're good to go ahead with that.

Nearly there!
