### ISSUE TITLE
Dates in local time including offset from UTC (ISO 8601)

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#34]
For each date, instead of providing them like this:
```
"end": {
   "date": "2016-01-21 00:00:13.000000",
   "timezone_type": 3,
   "timezone": "Europe/Copenhagen"
},
```
Simply ensure that the date is in [ISO 8601 in local time with an offset from UTC](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators):
```
"end": "2016-07-13T20:00:00-05:00",
```

Check out the [Implementation Checklist](https://github.com/openactive/realtime-paged-data-exchange/blob/master/README.md#implementation-checklist) for similar things to check

**Comment by nickevansuk** [comment]
Sorry to make this clearer, you can use either local time or UTC - keeping local time makes more sense for your use case as you are international

**Comment by TheLegendOfProgramming** [comment]
What about the "modified"? Should it be TimeStamp, DateTime or ISO 8601 ?

**Comment by nickevansuk** [comment]
Looks good
