### ISSUE TITLE
All URLs should be absolute

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#36]
```
"image": "/images/bg.png",
```

I assume the above is test data, but just in case it isn't:
- All URLs should be absolute
- For image URLs, empty string should be returned instead of placeholder images when there is no image available

**Comment by nickevansuk** [comment]
```
"image": "/images/bg.png",
```

This is still present in the feed

**Comment by TheLegendOfProgramming** [comment]
Can you leave the specific example so i can look for it please? I tried reviewing each item and I couldn't find it.

**Comment by nickevansuk** [comment]
I can't find it now either, assume this was fixed and i was looking at a cached page.
