### ISSUE TITLE
Get yourself a Dataset Site

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#37]
This looks like it's nearly there now, so there's one more quick thing you need to sort.

Check out the steps at the bottom of this page: https://github.com/openactive/dataset-site-generator/wiki

This will give you something that looks like this: http://data.goskyride.com

**Comment by TheLegendOfProgramming** [comment]
Dataset Site can be found live here: 
athliit.github.io 
         
          or

data.athliit.com
