### ISSUE TITLE
Give openactive-bot permission to update

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#38]
Noticed you missed the step in "Creating a GitHub account and GitHub organisation" where you give openactive-bot permission to update your Dataset Site.

Please either:
- Give openactive-bot permission to the https://github.com/flex-tv/flex-tv.github.io repo (see page 2 of [this guide](https://docs.google.com/document/d/1L6_YIQfQJjlmS1uXDDWGRW-EkdcBZRnxpeXLMqfDxVc/edit#), recently updated)
- Make openactive-bot a member of your organisation: https://github.com/flex-tv (see page 4 of [this guide](https://docs.google.com/document/d/1pM8fse2x_grSulLPzQ2J5S_iTZH2LrnWcmEA0J0xTgI/edit#heading=h.b2971ylun8i4))

**Comment by ElliottJPerry** [comment]
Think I skipped that guide, good call adding it to the "Creating a Dataset Site" guide. Let me know that this is sorted and that openactive-bot has access as a collaborator on the repo :)

**Comment by nickevansuk** [comment]
perfect, bot's just updated it so works
