### ISSUE TITLE
UTC Timestamp

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#53]
```
"modified": "2015-12-17 00:14:56",
```

should be

```
"modified": "2015-12-17T00:14:56",
```

Check out the [Implementation Checklist](https://github.com/openactive/realtime-paged-data-exchange/blob/master/README.md#implementation-checklist) for similar things to check.

**Comment by northernpaul** [comment]
Modified timestamp has been updated to UTC format

**Comment by nickevansuk** [comment]
Just checked the stream http://bcrm.apps4.co.uk/apiopen/SessionStream - the modified timestamp appears to be unchanged, same issue also still in the next URL.

Am I using the right endpoint?

**Comment by northernpaul** [comment]
Endpoint is correct, have checked this morning and all dates are correct in UTC

**Comment by nickevansuk** [comment]
Great, looks good!
