### ISSUE TITLE
Paging broken

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#55]
The structure outside of the data is great, but the paging does not conform to the specification, as the next URL seems to be the same on each page? The afterTimestamp and afterID parameters appear to be ignored.

Please see [4.3.1](https://www.openactive.io/realtime-paged-data-exchange/#modified-timestamp-and-id), and also issue https://github.com/openactive/activation/issues/22 for more information.

**Comment by northernpaul** [comment]
The timestamp and ID should be correctly reflecting the last record now in the next field URL.

**Comment by nickevansuk** [comment]
The next URL reads:

```
/PagedActivityCategories?afterTimestamp=2015-12-17 00:14:56&afterId=68e0235f-4f29-4c6e-972b-c72de212b786&pageSize=10
```

Where the endpoint is `/apiopen/SessionStream`. Note that the next URL must be absolute, so this should read (with the ISO timestamp url encoded):
```
/apiopen/SessionStream?afterTimestamp=2015-12-17T00%3A14%3A56&afterId=68e0235f-4f29-4c6e-972b-c72de212b786&pageSize=10
```

**Comment by nickevansuk** [comment]
Also currently the parameters seem to be ignored? The following URLs return the same results (data from 2015):

- 2017: http://bcrm.apps4.co.uk/apiopen/SessionStream?afterTimestamp=2017-12-17%2000:14:56&afterId=05a10663-e9a0-43af-bcc2-cacb8182d6ff&pageSize=10
- 2016: http://bcrm.apps4.co.uk/apiopen/SessionStream?afterTimestamp=2016-12-17%2000:14:56&afterId=05a10663-e9a0-43af-bcc2-cacb8182d6ff&pageSize=10

**Comment by northernpaul** [comment]
This should be sorted now, timestamp and session ID are both changing dependent on recordset requested.  Please note, both the above queries will return an empty data set as the data only goes forward by around 3-4 months.

**Comment by nickevansuk** [comment]
Next URL still includes `/PagedActivityCategories`, if this is corrected we can do a more thorough check on the paging

**Comment by northernpaul** [comment]
Appologies, I’d missed that one – sorted now.

**Comment by nickevansuk** [comment]
Should be `/apiopen/SessionStream`, the whole path

**Comment by northernpaul** [comment]
No problem, that’s updated too

**Comment by nickevansuk** [comment]
Looking at the last page `/apiopen/SessionStream?afterTimestamp=2016-08-22T08%3A52%3A53&afterId=875f8e18-94a0-00d3-f0af-57babdbf9930&pageSize=10`, the next URL returns `/apiopen/SessionStream?afterTimestamp=&afterId=&pageSize=10`.

The next URL of the last page should be the same as the page itself. The last page should have empty `items`, with the same next URL as the one used to call the page.

Any client will just keep following the next URLs, so they all need to be valid, even the last one.

**Comment by northernpaul** [comment]
Ok, that’s changed now – the nextURL of the last (empty) page uses the same nextURL as the call.

**Comment by nickevansuk** [comment]
This is looking pretty good now, will do some slightly more thorough testing and come back.
