### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#56]
This is probably already in the agreed specification for IWIYW, but I thought I'd check anyway. The data seems a little light on detail - e.g. Gender, Disabilities, Min Age, Max Age, Price, Session URL (link to a website where a user can find out more). 

The Session URL is especially for finding out more details not included in the description.

Are these not included in the spec?

**Comment by northernpaul** [comment]
This information currently isn't recorded in the CRM for the activities.  There's no reason why it can't be - just currently outside of spec.
