### ISSUE TITLE
"modified" should be included in each item

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#79]
"modified" should be included in each item, with the value of the rowversion

This will also allow your feed to pass the schema validator http://validator.openactive.io

**Comment by peteypops** [comment]
We don't have a modified date on the record set.

**Comment by nickevansuk** [comment]
Sorry I meant the "rowversion" field contents - "modified" is only used for caching so rowversion is sufficient, doesn't need to be actual modified date

**Comment by nickevansuk** [comment]
Great!
