### ISSUE TITLE
Fix mailing list

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#89]
Add mailing list to dataset site

See https://github.com/openactive/dataset-site-generator/wiki

**Comment by makesweat** [comment]
Done

**Comment by nickevansuk** [comment]
Note that the Privacy Policy still points to British Cycling if you click the mailing list button. This can be edited inside Mailchimp

**Comment by makesweat** [comment]
Please close. Thanks.

**Comment by nickevansuk** [comment]
Great
