### ISSUE TITLE
Clubspark Example Endpoint

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#9]
Please add to this thread

**Comment by nickevansuk** [comment]
@dolkensp here's a starter for 10:

```
{
  "@context": [
    "https://www.openactive.io/ns/oa.jsonld",
    "https://www.openactive.io/ns-beta/oa.jsonld"
  ],
  "type": "Event", /* The top level event here is a 'course', fields here map to 'course' fields */

  "categories": "Mini Tennis",

  "activity": {
    "id": "http://openactive.io/activity-list/#f2ea7405-6098-4378-b0fe-4e398a659fc4",
    "type": "skos:Concept",
    "prefLabel": "Tennis",
    "inScheme": "https://www.openactive.io/activity-list/activity-list.jsonld"
  }, /* hard coded  */

  "offer": [
    {
      "type": "Offer",
      "name": "Full course", /* Hard coded */
      "identifier": "COURSE", /* Hard coded for override */
      "price": "60.00", /* fullCourseCost (+ lateJoiningSessionCost if in the past and lateJoiningEnabled) */
      "priceCurrency": "GBP", /* Hard coded */
      "url": "", /* url to book */
    },
    {
      "type": "Offer",
      "name": "Single session", /* Hard coded */
      "identifier": "SINGLE", /* Hard coded for override */
      "price": "6.60", /* perSessionCost (+ lateJoiningSessionCost if in the past and lateJoiningEnabled?) */
      "priceCurrency": "GBP", /* Hard coded */
      "url": "", /* url to book */
    }
  ],

  "identifier": "4e2ff99b-1eb7-4da8-af73-016ff914546d",

  "name": "Mini Tennis",

  "ageRange": "10-12",

  "theme": "Tots", /* TODO: add to beta? */
  "type": "Course", /* TODO: add to beta? */

  "url": "", /* url of course page */

  "organizer": {
    "type": "Organization",
    "identifier": "193a4028-bd3d-48d2-87de-01686d8377c4",
    "name": "Bar Lawn Tennis Society",
    "telephone": "02074215300",
    "email": "jonathanupton@tanfieldchambers.co.uk.ltatest"
  },

  "location": {
    "type": "Place",
    "identifier": "c0a626f0-8778-4916-8b06-00092a3301e7",
    "name": "Warriston Community Tennis Club",
    "address": {
      "type": "PostalAddress",
      "addressLocality": "Edinburgh",
      "postalCode": "EH3 5LA"
    },
    "geo": {
      "latitude": 55.958561,
      "longitude": -3.20392
    }
  },

  "programme": "Junior",

  "level": "All", /* Skill level */

  "eventStatus": "http://schema.org/EventScheduled", /* one of "http://schema.org/EventScheduled" (status=Active), "http://schema.org/EventCancelled" (status=Cancelled) */

  "genderRestriction": "mixed",

  "description": "", 

  "subEvent": [ /* each session is a subEvent */
    {
      "start": "2015-06-30T08:30:00Z", /* note best UTC without timezone */
      "end": "2015-06-30T11:30:00Z", /* note best UTC without timezone */
      "identifier": "9107cd54-7e89-405c-8c2b-026988099ff8",
      "location": { /* Include if overriden */
        "type": "Place",
        "identifier": "c0a626f0-8778-4916-8b06-00092a3301e7",
        "name": "Warriston Community Tennis Club",
        "address": {
          "type": "PostalAddress",
          "addressLocality": "Edinburgh",
          "postalCode": "EH3 5LA"
        },
        "geo": {
          "latitude": 55.958561,
          "longitude": -3.20392
        }
      },
      "name": "group 1 classes",
      "description": "", 
      "eventStatus": "http://schema.org/EventScheduled", /* one of "http://schema.org/EventScheduled" (status=Active), "http://schema.org/EventCancelled" (status=Cancelled) */

      "url": "", /* url of session page */

      "offer": {
        "type": "Offer",
        "name": "Single session", /* Hard coded */
        "identifier": "SINGLE", /* Hard coded for override */
        "price": "6.00", /* single session cost */
        "priceCurrency": "GBP", /* Hard coded */
        "url": "", /* url to book */
      },
    }
  ]
}
```

**Comment by dolkensp** [comment]
Here is the current sample I have working.

Still need to confirm some pricing logic with the team.

[courses.json.txt](https://github.com/openactive/activation/files/1134325/courses.json.txt)

Haven't got the bookings feed running just yet.

Added the **eligibleCustomerType** property to Offers where necessary to indicate when member-only pricing was supplied.

**Comment by nickevansuk** [comment]
Looks good! In terms of **eligibleCustomerType**, http://purl.org/goodrelations/ (referenced from schema.org) doesn't seem to have adequate vocab for this. Suggest we add terms to beta, e.g.

- https://www.openactive.io/ns-beta#Member

Let me know the list of terms you've used - Member is a great one - and I can add them to Beta (or please do so via https://github.com/openactive/ns-beta/issues).

One other point to note: there aren't any URLs in the events or offers as yet...

**Comment by dolkensp** [comment]
I've just used "Member" here as a generic term, but I'd also consider just using the name of the specific Membership Packages (which are user defined) for this value.

So "Members", "Everyone", "Administrators" might be common generic terms based on our current uses, but "2017 Junior Membership" might be an example of a more specific term.

I don't believe we offer this package-specific pricing scheme for Courses currently, but we certainly do for other parts of the system, such as court-access bookings; So it's believable that it may come to courses in the future.

**Comment by dolkensp** [comment]
Here is the pricing configuration for court bookings, where you can see the different values available for a single club:

![image](https://user-images.githubusercontent.com/469666/28011376-00ab3602-655a-11e7-9171-c401a0774e2b.png)

Everyone, All Members, and Booking Administrators are all System values, the rest are user-controlled.

**Comment by nickevansuk** [comment]
Very interesting @dolkensp - perhaps we stick to just "https://www.openactive.io/ns-beta#Member" for now to distinguish them from non member offers?

Representing membership purchase options certainly something to think about in the future, for now it is sufficient to mark offers as "member only" in this way, and then provide a URL in the offer that takes you to the membership purchase screen (for all membership types).

**Comment by dolkensp** [comment]
Another thing that may affect this - member pricing may end up being redacted - I'll need to check with the team on that, as some venues may not want their pricing structure exposed if we do allow the more complex pricing logic.

**Comment by nickevansuk** [comment]
That makes sense - probably not relevant to publish full member pricing, but rather just a "From £5" type of thing with a link to find out more about membership. The point of publishing member pricing is for an upsell option, rather than for the user to get granular understanding of it.
