### ISSUE TITLE
Add documentation page in GitHub

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#90]
Create a new repo with a readme.md file similar to https://github.com/fusion-lifestyle/opendata (use that file as a template)

**Comment by makesweat** [comment]
Done

**Comment by nickevansuk** [comment]
This needs to be updated to match your own dataset, it currently linked to Fusion

**Comment by makesweat** [comment]
Please close.

**Comment by nickevansuk** [comment]
Great!
