### ISSUE TITLE
meetingPoint

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#94]
```
"meetingPoint ": "Class takes place in the room above the pub - sadly not in the bar itself! Access by entering pub, and going through the door on your right at the end of the bar."
```

`meetingPoint` should be in the event rather than in the location or address. Also should not include the space at the end of the key.

**Comment by makesweat** [comment]
Fixed. I'm not sure that this is really the right data for meetingPoint, but happy to include it.

**Comment by nickevansuk** [comment]
The other option is "description" in the location? Would that fit better?

**Comment by makesweat** [comment]
I think it would. The meeting point is defined by the lat/lon/address in the location.

**Comment by nickevansuk** [comment]
Brilliant, that looks like the last change in that case

**Comment by makesweat** [comment]
meetingPoint moved to location->description

**Comment by nickevansuk** [comment]
Great!
