### ISSUE TITLE
Plain text descriptions include not-so-plain text

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#97]
`"description": "__This booking facility is for <u>members only</u>__.,`

Some descriptions have interesting characters

**Comment by jopotts** [comment]
Hi @nickevansuk Can you obfuscate the customer data at this stage until it's live opted-in data please. Thanks.

**Comment by nickevansuk** [comment]
Apologies Jo, will take down the example above

**Comment by nickevansuk** [comment]
Note `&amp;` can still be found in the description field

**Comment by nickevansuk** [comment]
Great!
